# Freebuff Desktop icon — installs the 512x512 Freebuff icon into the
# hicolor theme so the .desktop entry's Icon=freebuff resolves.
#
# The .desktop entry itself is generated by home-manager-config's
# appimage-updater.nix (xdg.desktopEntries). This module only provides
# the icon asset — data, not launcher logic.
{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.services.freebuff-desktop;

  freebuff-icon = pkgs.runCommand "freebuff-icon" {} ''
    mkdir -p "$out/share/icons/hicolor/512x512/apps"
    cp ${./assets/freebuff-icon.png} "$out/share/icons/hicolor/512x512/apps/freebuff.png"
  '';
in {
  options.services.freebuff-desktop = {
    enable = mkEnableOption "Freebuff Desktop icon (hicolor theme)";
  };

  config = mkIf cfg.enable {
    environment.systemPackages = [ freebuff-icon ];
  };
}
