# TP-Link Smart Switch Management Service
# Provides Playwright-based automation for TP-Link Easy Smart Switches
# Switches at: 10.1.1.10, 10.1.1.11, 10.1.1.12, 10.1.1.13
{
  config,
  lib,
  pkgs,
  ...
}: let
  inherit (lib) mkOption types mkIf mkEnableOption;

  cfg = config.services.tplinkSwitches;
in {
  options.services.tplinkSwitches = {
    enable = mkEnableOption "TP-Link Smart Switch management service";

    # Switch configurations
    switches = mkOption {
      type = types.attrsOf (types.submodule {
        options = {
          ip = mkOption {
            type = types.str;
            description = "IP address of the switch";
          };
          name = mkOption {
            type = types.str;
            description = "Human-readable name for the switch";
          };
          username = mkOption {
            type = types.str;
            default = "admin";
            description = "Username for switch web interface";
          };
          password = mkOption {
            type = types.str;
            default = "admin";
            description = "Password for switch web interface";
          };
          ports = mkOption {
            type = types.listOf (types.submodule {
              options = {
                port = mkOption {
                  type = types.int;
                  description = "Port number (1-5)";
                };
                vlan = mkOption {
                  type = types.int;
                  description = "VLAN ID for this port";
                };
                name = mkOption {
                  type = types.str;
                  description = "Port description";
                };
              };
            });
            default = [];
            description = "Port configurations";
          };
        };
      });
      default = {
        switch1 = {
          ip = "10.1.1.10";
          name = "tl-sg105e-1";
        };
        switch2 = {
          ip = "10.1.1.11";
          name = "tl-sg105e-2";
        };
        switch3 = {
          ip = "10.1.1.12";
          name = "tl-sg105e-3";
        };
        switch4 = {
          ip = "10.1.1.13";
          name = "tl-sg105e-4";
        };
      };
      description = "Switch configurations";
    };

    # VLAN definitions
    vlans = mkOption {
      type = types.listOf (types.submodule {
        options = {
          id = mkOption {
            type = types.int;
            description = "VLAN ID";
          };
          name = mkOption {
            type = types.str;
            description = "VLAN name";
          };
        };
      });
      default = [
        {id = 10; name = "gaming";}
        {id = 20; name = "ai";}
        {id = 30; name = "storage";}
        {id = 40; name = "mining";}
        {id = 50; name = "monitoring";}
        {id = 60; name = "backup";}
        {id = 99; name = "management";}
      ];
      description = "VLAN configurations to create on switches";
    };

    # Monitoring settings
    monitoring = mkOption {
      type = types.submodule {
        options = {
          enable = mkEnableOption "Switch monitoring";
          interval = mkOption {
            type = types.int;
            default = 300; # 5 minutes
            description = "Polling interval in seconds";
          };
      #   prometheusExporter = mkEnableOption "Prometheus metrics exporter";
        };
      };
      default = {};
    };

    # Automation settings
    automation = {
      enableAutomatedConfig = mkEnableOption "Automatic switch configuration";
      headless = mkOption {
        type = types.bool;
        default = true;
        description = "Run Playwright in headless mode";
      };
    };
  };

  config = mkIf cfg.enable {
    # ============================================================================
    # SYSTEM PACKAGES
    # ============================================================================
    environment.systemPackages = with pkgs; [
      # Core Python with Playwright
      (python3.withPackages (ps:
        with ps; [
          playwright
          requests
          urllib3
        ]))

      # Utility packages
      playwright
      ffmpeg # Required for Playwright video recording
    ];

    # ============================================================================
    # TPLINK SWITCH AUTOMATION WRAPPER SCRIPTS
    # ============================================================================
    environment.etc."tplink-switches/automate.py" = {
      text = ''
        #!/usr/bin/env python3
        """
        TP-Link Switch Automation Wrapper
        Generated by NixOS tplinkSwitches module
        """

        import asyncio
        import json
        import os
        import sys
        from pathlib import Path
        from typing import Optional, Dict, Any, List

        try:
            from playwright.async_api import async_playwright, Browser, Page
        except ImportError:
            print("ERROR: Playwright not installed")
            sys.exit(1)

        # Configuration from NixOS
        SWITCHES = ${builtins.toJSON cfg.switches}
        VLANS = ${builtins.toJSON cfg.vlans}
        HEADLESS = ${lib.boolToString cfg.automation.headless}

        class SwitchAutomator:
            """Automate TP-Link Easy Smart Switch via Playwright"""

            def __init__(self, ip: str, username: str, password: str, name: str = ""):
                self.ip = ip
                self.username = username
                self.password = password
                self.name = name
                self.base_url = f"http://{ip}"

            async def login(self, page: Page) -> bool:
                """Login to switch web interface"""
                try:
                    await page.goto(self.base_url, timeout=15000)
                    await page.wait_for_load_state("domcontentloaded", timeout=5000)

                    # Wait for login form
                    await page.wait_for_selector('input[name="username"]', timeout=5000)
                    await page.fill('input[name="username"]', self.username)
                    await page.fill('input[name="password"]', self.password)
                    await page.click('input[name="logon"]')
                    await page.wait_for_load_state("domcontentloaded", timeout=5000)

                    # Check if login succeeded
                    current_url = page.url
                    if "/logon.cgi" not in current_url:
                        print(f"  ✓ Logged into {self.name or self.ip}")
                        return True
                    return False
                except Exception as e:
                    print(f"  ✗ Login failed: {e}")
                    return False

            async def get_port_status(self, page: Page) -> List[Dict[str, Any]]:
                """Get status of all ports"""
                try:
                    await page.goto(f"{self.base_url}/portRpm.htm", timeout=15000)
                    await page.wait_for_load_state("domcontentloaded", timeout=5000)
                    await asyncio.sleep(1)

                    ports = []
                    for port_num in range(1, 6):  # 5-port switches
                        port_info = {"port": port_num, "enabled": False, "link": False}
                        ports.append(port_info)

                    return ports
                except Exception as e:
                    print(f"  ✗ Error getting port status: {e}")
                    return []

            async def get_system_info(self, page: Page) -> Dict[str, Any]:
                """Get system information"""
                try:
                    await page.goto(f"{self.base_url}/sysRpm.htm", timeout=15000)
                    await page.wait_for_load_state("domcontentloaded", timeout=5000)
                    await asyncio.sleep(1)

                    # Try to extract system info
                    info = {
                        "ip": self.ip,
                        "name": self.name,
                        "model": "TL-SG105E",
                        "mac": "",
                        "firmware": "",
                    }

                    return info
                except Exception as e:
                    print(f"  ✗ Error getting system info: {e}")
                    return {}

            async def enable_snmp(self, page: Page) -> bool:
                """Enable SNMP on switch"""
                try:
                    await page.goto(f"{self.base_url}/snmpRpm.htm", timeout=15000)
                    await page.wait_for_load_state("domcontentloaded", timeout=5000)
                    await asyncio.sleep(1)

                    enable_selectors = [
                        'input[name="snmpEnable"]',
                        'input[type="checkbox"][name*="snmp"]',
                        "#snmpEnable",
                    ]

                    for selector in enable_selectors:
                        try:
                            element = await page.query_selector(selector)
                            if element:
                                is_checked = await element.is_checked()
                                if not is_checked:
                                    await element.check()
                                    print(f"  ✓ SNMP enabled")
                                    return True
                        except Exception:
                            continue

                    return False
                except Exception as e:
                    print(f"  ✗ Error enabling SNMP: {e}")
                    return False

            async def create_vlan(self, page: Page, vlan_id: int, vlan_name: str) -> bool:
                """Create a VLAN on the switch"""
                try:
                    await page.goto(f"{self.base_url}/vlanRpm.htm", timeout=15000)
                    await page.wait_for_load_state("domcontentloaded", timeout=5000)
                    await asyncio.sleep(1)

                    # Try to find and click Add button
                    add_selectors = [
                        'input:has-text("Add")',
                        'button:has-text("Add")',
                        'a:has-text("Add")',
                    ]

                    for selector in add_selectors:
                        try:
                            element = await page.query_selector(selector)
                            if element:
                                await element.click()
                                await asyncio.sleep(1)
                                break
                        except Exception:
                            continue

                    # Fill VLAN form
                    vlan_id_input = await page.query_selector('input[name*="vid"]')
                    vlan_name_input = await page.query_selector('input[name*="vname"]')

                    if vlan_id_input:
                        await vlan_id_input.fill(str(vlan_id))

                    if vlan_name_input:
                        await vlan_name_input.fill(vlan_name)

                    # Save
                    save_selectors = [
                        'input:has-text("Apply")',
                        'button:has-text("Apply")',
                        'input[value="Apply"]',
                    ]

                    for selector in save_selectors:
                        try:
                            element = await page.query_selector(selector)
                            if element:
                                await element.click()
                                await page.wait_for_load_state("domcontentloaded", timeout=5000)
                                print(f"  ✓ VLAN {vlan_id} ({vlan_name}) created")
                                return True
                        except Exception:
                            continue

                    return False
                except Exception as e:
                    print(f"  ✗ Error creating VLAN: {e}")
                    return False

            async def take_screenshot(self, page: Page, filename: str):
                """Take a screenshot for debugging"""
                screenshot_dir = Path("/var/cache/tplink-switches/screenshots")
                screenshot_dir.mkdir(parents=True, exist_ok=True)
                await page.screenshot(path=str(screenshot_dir / f"{filename}.png"))
                print(f"  📷 Screenshot saved: {filename}.png")

        async def configure_switch(switch_key: str, switch_config: Dict[str, Any]):
            """Configure a single switch"""
            ip = switch_config["ip"]
            name = switch_config.get("name", ip)
            username = switch_config.get("username", "admin")
            password = switch_config.get("password", "admin")

            print(f"\n{'='*60}")
            print(f"Configuring switch: {name} ({ip})")
            print(f"{'='*60}\n")

            automator = SwitchAutomator(ip, username, password, name)

            async with async_playwright() as p:
                browser = await p.chromium.launch(headless=HEADLESS)
                page = await browser.new_page()

                # Login
                if not await automator.login(page):
                    await automator.take_screenshot(page, f"{name.replace('.', '-')}-login-error")
                    await browser.close()
                    return False

                await asyncio.sleep(1)

                # Enable SNMP
                print("Enabling SNMP...")
                await automator.enable_snmp(page)

                # Create VLANs
                print("\nCreating VLANs...")
                for vlan in VLANS:
                    print(f"  Creating VLAN {vlan['id']} ({vlan['name']})...")
                    await automator.create_vlan(page, vlan['id'], vlan['name'])

                # Take final screenshot
                await automator.take_screenshot(page, f"{name.replace('.', '-')}-complete")

                await browser.close()
                return True

        async def monitor_switch(switch_key: str, switch_config: Dict[str, Any]):
            """Monitor switch status"""
            ip = switch_config["ip"]
            name = switch_config.get("name", ip)
            username = switch_config.get("username", "admin")
            password = switch_config.get("password", "admin")

            automator = SwitchAutomator(ip, username, password, name)

            async with async_playwright() as p:
                browser = await p.chromium.launch(headless=HEADLESS)
                page = await browser.new_page()

                if await automator.login(page):
                    info = await automator.get_system_info(page)
                    ports = await automator.get_port_status(page)

                    print(json.dumps({
                        "switch": name,
                        "ip": ip,
                        "info": info,
                        "ports": ports,
                        "timestamp": __import__("time").time()
                    }, indent=2))

                await browser.close()

        async def main():
            """Main entry point"""
            if len(sys.argv) < 2:
                print("Usage: automate.py <command> [options]")
                print("Commands:")
                print("  configure [switch_key]   Configure switch(es)")
                print("  monitor [switch_key]      Monitor switch status")
                print("  status [switch_key]       Get switch status (JSON)")
                print("  screenshot [switch_key]   Take screenshot")
                sys.exit(1)

            command = sys.argv[1]
            switch_key = sys.argv[2] if len(sys.argv) > 2 else None

            if command == "configure":
                if switch_key:
                    if switch_key in SWITCHES:
                        await configure_switch(switch_key, SWITCHES[switch_key])
                    else:
                        print(f"Error: Switch '{switch_key}' not found")
                        sys.exit(1)
                else:
                    for key, config in SWITCHES.items():
                        await configure_switch(key, config)

            elif command == "monitor" or command == "status":
                if switch_key:
                    if switch_key in SWITCHES:
                        await monitor_switch(switch_key, SWITCHES[switch_key])
                    else:
                        print(f"Error: Switch '{switch_key}' not found")
                        sys.exit(1)
                else:
                    for key, config in SWITCHES.items():
                        await monitor_switch(key, config)

            elif command == "screenshot":
                # Take screenshots of all switches
                async with async_playwright() as p:
                    browser = await p.chromium.launch(headless=HEADLESS)

                    for key, switch_config in SWITCHES.items():
                        ip = switch_config["ip"]
                        name = switch_config.get("name", ip)
                        username = switch_config.get("username", "admin")
                        password = switch_config.get("password", "admin")

                        automator = SwitchAutomator(ip, username, password, name)
                        page = await browser.new_page()

                        if await automator.login(page):
                            await automator.take_screenshot(page, f"{name.replace('.', '-')}-snapshot")

                    await browser.close()

            else:
                print(f"Unknown command: {command}")
                sys.exit(1)

        if __name__ == "__main__":
            asyncio.run(main())
      '';
      mode = "0755";
    };

    # ============================================================================
    # SYSTEMD SERVICE FOR MONITORING
    # ============================================================================
    systemd.services.tplink-monitor = lib.mkIf cfg.monitoring.enable {
        description = "TP-Link Switch Monitor";
        after = ["network-online.target"];
        wants = ["network-online.target"];
        serviceConfig = {
          Type = "simple";
          User = "root";
          ExecStart = "/etc/tplink-switches/automate.py status";
          Restart = "on-failure";
          RestartSec = "60s";

          # Security hardening
          ProtectSystem = "strict";
          ProtectHome = true;
          PrivateTmp = true;
          NoNewPrivileges = true;
        };
      };

    systemd.timers.tplink-monitor = lib.mkIf cfg.monitoring.enable {
        description = "TP-Link Switch Monitor Timer";
        wantedBy = ["timers.target"];
        partOf = ["tplink-monitor.service"];
        timerConfig = {
          OnUnitActiveSec = "${toString cfg.monitoring.interval}s";
          OnBootSec = "60s";
        };
      };

    # ============================================================================
    # CACHE DIRECTORY FOR SCREENSHOTS
    # ============================================================================
    systemd.tmpfiles.rules = [
      "d /var/cache/tplink-switches 0755 root root -"
      "d /var/cache/tplink-switches/screenshots 0755 root root -"
    ];

    # ============================================================================
    # NETWORK CONSTANTS - Add switch IPs to cluster network
    # ============================================================================
    networking.extraHosts = lib.optionalString cfg.enable ''
        ${lib.concatMapStringsSep "\n" (switch: "${switch.ip} ${switch.name}") (lib.attrValues cfg.switches)}
      '';
  };
}
