#ENC[AES256_GCM,data:r3jsMLI88IUwLK6Atzvi0SyWgTiZYO64s1KCogzQi8CKoSCl337x9Xk2q1MggEcZXe7sMAV52+d48jTVnMkVzVDXkw==,iv:6w1ItJYNctWWqlMYvsazdysA9NGKEmI9GAx3XBwbGaQ=,tag:vdt4X1HDfD3nsfzkZJYftw==,type:comment]
#ENC[AES256_GCM,data:D6j+LMXcz1XbL0Plq+8n8xP4UQngRQrMpiXGnkbFrYDn4GDiIbamtWKmJi/yGPziiwdlILRXi45ye4MmyZiVI87zYw==,iv:lAelPDb7QE3GfmpDE7XUaQc1SmFE52KBqbyUwQ3LNSE=,tag:EyaWlrAvLwvSfgfo6WAaDQ==,type:comment]
#ENC[AES256_GCM,data:4m+OX6WmukmM5ZymhgrVekidVvSu+mP9vnwWcPtKSaNvgMiJSKOV3WvvAyvmLaA=,iv:GJJBGtpqB77f3Nh7qF+UH0izZYIgMkM59fpw7NBjv7g=,tag:Lb4BaTMMdjRT9+dg98RQ4Q==,type:comment]
initrd_ssh_host_key_nexus: ENC[AES256_GCM,data:Y/h3HEChVSq5y2+iXXVhn1I1sdGmHTerKiT48K/Wqq2qGNeBiY8=,iv:iZl2D5LnQqOpYTDxOys44fBEmhW40sogUYslq/Cud2w=,tag:6je/o//DuaMhY1Xt0eO4Yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyakVseEE5eW5uMDFPVHpJ
            L3BQcE16M2dqZG9GUmppcjNMUDRKQ2xYQ1VrCnNabzJvY3gxT0NoZjhDQXJ0YVJK
            S3l3WkFUcFRnRHVMWWN6Lzd4em1FbmMKLS0tIDhNVGlJK1F6T1VQTS9jT3BrMmJO
            ZVMrdmRiSjBGNTJKR1dROU83TjMxZXcKlMFOLWXwq7wYp2Iof7MqSm+58fNTnPuW
            hRwCBGtxoEpIA7mCnANZAgViUYu6QS5q98yURx1IaXn2wglC1Yu74w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RE8xQTdnOXl5UlVRYzdk
            Nk02YzJEcnhwUUlOYjVuYVZtL3lOTWJiSXlVClFXN0F6Zll4Y1BqbksrUEhrbDBq
            dy9wUmFKOUhjdVdIQmM1RjRLUEYvYmMKLS0tIHdDbno1UDRzc1o2OU5ET0d4djNH
            bHBTbWFpQU9Canp6RGVJMWpXNXJ1WkEKmI3eq0qJcOQZlR6q2cWy3aHHxUOpiVzC
            bcPdE80WKXVQ7b3TFnIawSXOLLZg1rsfKbFShGyYfkuoc9vsmnXiwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBMG9UQUNY
            SG5YWC9xWFBTWjFxekRVQldxWGVxSGpKc3cxUGE4K1VwSjJweAoycmFla0hweERh
            c0laTjhocHRHbURkRTFoMkprQjMxVGNDRVE1V2pBTXRNCi0tLSBweFd0Z0I5dWlL
            UDFxOVNVUDd5OWIvT2Zqc08zQzlDRjdhRi85WGM0VzIwCv0c4iao3UqZFoY5oYbw
            Y9ulmk5eAcYQz3Zn0ZFGw7kNNGegLr9UUD41Wzh/Ku/jV6Wbj4lJ/HKMBmMvyx1q
            m7g=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBcDd0VXVY
            eW00VVhsaTZ0OXZoMkE2U1k5dlUzZ3VUUGZYdnRsYWZRTlAzMwpxekFxRGZ6Z3R3
            YUtjQ0Y0S3VWVWFZSGpQNENWSjZxa2hlK3c5Z3J5dEJzCi0tLSA4SnV5cWNnZnY2
            eXdXaklHLzhzdW1HVVlWTERVN1prQmd1bDNycnJSLzNRClFrO4Lkmx4bwKxvwTWJ
            o3tH7Rbgshmrw7yqZ/aXi+0qXtLWPVt5hQKIhDWAiT0H7Z7i+B77v6YM058YnY5G
            FC4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-07-25T18:48:29Z"
    mac: ENC[AES256_GCM,data:VS2i5avLghJepHtYKe16HmK5za7+Ll71HjHTowQUdUZHZW5pwsiERPhAORG77ujzyeR9bOfh6fz4U8vQfRMDrBnGyLEuCMA4V9KHpoXeluh0nZQDzJr8N8YNLX0hPSJ8NkcSXSeKp6ibhmOy8/vfSbTVDZnaEnpFhJetpzKpGV0=,iv:vtWK3PYeHYPFq2rBbtfridYx2VU3WY56qv2HcCG7D2w=,tag:fQshiuBK1ghBc0/XZt6R4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
