#ENC[AES256_GCM,data:1fFgZwo11gos4xrdJA10a5SVYOD6Yl61QPMRJv6T0ub23GWYca9k+bDcSasHZIcmH5YOOQKZEG5wOxgeMxfOF6Vn2A==,iv:ohDXVzoPhzoBB+gw4J0nfRsMO22pMfEZ3zv+1tp6HQs=,tag:L9C5TKVFysvIWK6avcx2aw==,type:comment]
#ENC[AES256_GCM,data:2/r5r+Ph3FxBiaAyc0cYmFptI1yMojcc7iJHx2FWhV5PRLyPJ7rkxHq87E/kb0tOgVaIvi2jaRFfe+UYndZ0/Dw6Yw==,iv:BkqBhNZEBPEMB7xZU1uLYdWr3z3eVY9C2N3HbsrQubo=,tag:gFaAUlsx/An52vM+26uWiw==,type:comment]
#ENC[AES256_GCM,data:pyS7j2Dr+d5i7Db5WvoBcfR9S01Ng0R+IOv5JB3Rn1Mu+l5ND3CWAwQ9QpGr+HQ=,iv:s4Y7P3e4pVotcLqktXH8ijAFcRyfcfzlc+6TdoKA7dg=,tag:LOjqUO74T7+4SdMvsPVSJA==,type:comment]
switch_admin: ENC[AES256_GCM,data:qENM0PjgzQanH8PjJ8ctomWmZIaIryj19keUy/obZcYtjcVBwjo=,iv:PiRno14NS44Y1WkzEN3EuefFlNSsjOn3+Le7AZkSeLs=,tag:rALCTLy5C3p06BAhPah+8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTkF3cEVWZzRlOXVyS3lB
            L0VKaEo5aE1SdUxtWmhweGVFUmRFem1vOGlBCkVEWmRhSThtR1dlT2hkYm9OckxW
            K3dtRmtsZFZ5WkdvVkZ2R2hNeFpuK2MKLS0tIFpsZWVlYmxLSWNXcEhHbDVnclA4
            NW1yYnliZkt1c2xtSXE1QmJ2YnZiMVUK1C/JVr4fwRWgsLbUP+OUn8Ountv4WTXv
            8LtvlsXzyMsPpto5OE1pjkFtEPd35Ol6yQ5q/7GQjdIxn1Voc8VT4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBL3dJSXA4
            N1Fpa3NjOHZNUTc1VEErYkYrMnZmN092b3R0dnpPWXR5ZlhTKwpRY214YkhsN09O
            S1VPcVp1L3BjcXNVcHlqVzhyWHorTnlTVTkvUHBXU2k4Ci0tLSA0czhvTW16Nzd0
            SU43cFI4aEdwMjAwN2phTlNPb0FKcDEvb3h6a0pKL2RrCkwpda9fwFgoDWlZ6gM6
            JzIvPeb/B9wDSbTYxfP1+PI0+n0sTqkvJKR9dSiEyN/5E4bacyAMbKf/6edgsbnB
            zY4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBNXRmTEZW
            YXpWVzh3Uk1YZWRlT1JvOWhoOFEwU2dyQ1lObG9yU2MwTVoragpvRVFSZER4RUgx
            WFRsTmdyOTZIbUI0NjBaZTZVd2dWWVFKQWVIYUhwenNrCi0tLSAyNU9RODREVk96
            RFUyZkFIU1NwR3N5Y0kvNERWaHNqdUpSdHRkSEdnaEZFCmOTld8Xaw5LBvTd+pUV
            eELd40p+a/Gfx8L4beA0PI5DTOc/gY+cu0lFOybYrkO2Fmt9sUdLsnouyPTu+wsf
            8bo=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-07-25T18:48:29Z"
    mac: ENC[AES256_GCM,data:YKhgnW/ANbhPpKvvWnBTuyKDIN7qOg0lDkXtLxNan9SwEliii7A3sKy+rVGbIQRbf+pOvP1DjOD/eFZ3/QEEcsoPiYmfKWoFSeRYZuoWCDWjLny1zgGcNwEW6M22i4J18JCjJjjNJs5PLD78NWf4ujafp23AkgAS/sVj+CLBQqI=,iv:E3B8Y9XcdcXu4gxac4vXNC1h/jzB5ibO00zuAopIB10=,tag:Chi590tbcIQY1A2y95rZoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
