# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usbcore" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b07258b9-b1a3-4540-ae34-69e441faba28";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/4bd91588-d1ed-4cd9-9cdd-86d515a12cb3";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/4bd91588-d1ed-4cd9-9cdd-86d515a12cb3";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b07258b9-b1a3-4540-ae34-69e441faba28";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/data/hermes" =
    { device = "/home/@home/j_kro/.hermes";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/data/models" =
    { device = "/home/@home/j_kro/.lmstudio/models";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/data/pi" =
    { device = "/home/@home/j_kro/.pi";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EB7C-E7CC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
