apiVersion: v1
kind: Pod
metadata:
  name: test-sa
  namespace: akash-provider
spec:
  serviceAccountName: akash-provider
  containers:
  - name: test
    image: bitnami/kubectl:latest
    command: ["sleep", "3600"]
