{
	"data": "ENC[AES256_GCM,data:VGrn5Spe1Nf5jRdS/CWf2RYKnQKsEGVPzN28yf15HT1YzcLc4z/B5r/BJM7kLET5CI4=,iv:nixTiE/KThwAjl1a7cAuWJRU56EUglq2fZo3sRfM+Ts=,tag:UywikLFUahzEBSCDGfA1zA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcnlyZ2UweFlUNTZDVlAz\nbzJWYm5ZdFNrNlN6Q3J5bkpKV0lLQzkxdEI4CkV4Y0tMTlJmY0kzUkFScmpLYjIv\nRG9rQ3B2UUFpamt2Vm1WcXNlYVlUYmcKLS0tIGVCN0c5bGNwNW15V05JcWtsYWFx\nNFVwOFp6bFBMSTQwQ2RPT3JzRFBtU2cKb7Q0bTEcxO2BBl40jmAXqopORonx5YaQ\nSKQqGp9SCP52cAJGdfiVuUf5QNy5tJBjiMQ9WPwNQrg3Ak8LO3+GBA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:58:59Z",
		"mac": "ENC[AES256_GCM,data:TAczsT0skqEUcp3Z4yrpSYYPK85WYIQo4j/BygCLCbYF4aZ7dfy3gzIPzA6Ph9tO8ZpelJfilRQy4TTMeGLBnX/8S5PxrM8xwZftmUZK9p1cHNMqar4wqlMtcnZ6tZDxP43k2qWuBHsK8elHT02deCU/+1EdMJqEuMg74S1Ig0U=,iv:jZhrUEA8Ibxi08Pt26TgYfxLJ43FozSWeUsgL4enL3k=,tag:F8BgcDcPZz54NnYONsWb+w==,type:str]",
		"version": "3.13.1"
	}
}
