data: ENC[AES256_GCM,data:6YtP6247m4pU0pc8ntynLCr3av6M9Ulzukyd7nkG3BxnXTyaj6nXxzqgM6MPLbdZSn9m/HQhjruXqytCQR1lHg==,iv:umvIB350lPbNZVKl8cnEPkAg5LNzqX4zl/gBxGqEzTA=,tag:neOLIBU0oBlRFrCKVgIqSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcUlnTmw4Y0RVaS9SdTJ6
            TTRWcXBTUk5yRzdvL3JVdWxNenovNlRiTTFvCkdLUWtKWmNkSTh4VDRrTDBmK0ZR
            WSsyN3Fxa2ltRlBSN1lLZ1FVRmVHRXMKLS0tIHo1Vlpuelh3NGtDeWVXaSt6bklC
            d0dxOGtTU0lGOTBjVm5IeGxhU21odFUKjbd+qnt3iguemZz1Ybgpzc3bl7g3uEFd
            UjbKViUGUf7qOZQse/fQwteLSNF4sPeql/cfPZysAUYAy/jx+KqWqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UXFwbFJKelk4YkFFNGkx
            RW5KbkxIKzlqQnE2QW1VTEMwZ1lJU2Q1Q1NjCkNDQUhwd2VhVTJheTYyQnp5Uytk
            S2o3YjBXS2tBRHdJazFtMjZnVkt6dDgKLS0tIHpQRUVtV0JObUh1WmdkbDFxcDJL
            aTRJR25jeVFnak9kTzhkdVo5SDA2b0EKMv9q0c0+OVlwZ0HKP0z1ZZz8O8m7tHUR
            lbgHaRLUQ8tbuUn726zHAG42C/CYbC24ZoWSg2Qs46MAWXPDxDkR3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
    lastmodified: "2026-08-16T04:33:24Z"
    mac: ENC[AES256_GCM,data:lI/dml+VhrKMusaeLoxNRBuDTbIioRJiX87ajtYcI2mAtdd9UlB792FX1FCdT9x5Bp+rpQ9M/XA1T6bfkSJwHWnNcbmzK+P7BzO2aB5jXjY2RBju35+7ZF0VPWTd4s5Nb4AIFSBk+8gkvZXpAvs2msK9stLPdtniiOzU4cvLpjo=,iv:6axLco68XngApDoBwBz2aKkKqUeWz7lkHdEY7c4NOz8=,tag:rGm5bW38GLWKDvOg/QVYsg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
