{
	"data": "ENC[AES256_GCM,data:ZolehJO1lvYpDSQ6t7jFqLlGMVZv3CZlswItVBvL28unSibUbnampXRlAuqs2Br6Bek8RNwccG3Pqw==,iv:5Uc3WpZrKFJd/dQKtRO3tutYnNv3x4RpLfsrJlnsUqk=,tag:OsxiHAZFzyiyQIfCHNhwoA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M1BGVDA4dUZxV0Z0WXJF\nSFRGaXRWUzRuUDRMakFpVXIraUV5T05jZWpvCjVrK0xmL3htWXRzMFM0ejlDYnlu\nTnhaZDlNaTNheUJmTUFBSzVIUjFEZ00KLS0tIDFsOUE2WGpWZTl6M2VKTjIxeWJX\neGlEMGFKMUsyUjdDOFJacWlrZDZZOEUKD/9LzLsAMewe7aJb5xpkYvKH2+/YE4Zc\n905gRaIQ+C43sMrDTok8E+OESqF1Mw2qRr4jD68p/SOQv4iFdSqX2A==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-07-15T06:33:43Z",
		"mac": "ENC[AES256_GCM,data:9MC4EaYVvRfBHal+FrFMyv5KLYo+PvItebqIVEd0B8X0ElMCLzXDfO90jiTMXSq4+0ZVkdv+KTT9CSSWJJnai9mWCNPpGEXrsJTfK3aY8LKZZspN3b/OyjFMJRmM9MGD22sOdLgUUXhXgN92krYQYgbsDsPxzDtK9soNuBeAObw=,iv:nA9r9APn6Vuwne2otvk1rvkrt0h2cytB6QjgDmKEgoY=,tag:Lzn0bb84Lxdz1F1tY6A8sA==,type:str]",
		"version": "3.13.1"
	}
}
