{
	"casdoor_maplespike_portal_client_secret": "ENC[AES256_GCM,data:6ZsZdxdh8f5nKVP8XZ+mEPgEZvB4gyfnUUdx0ncIPVKWwKSbIkA=,iv:kiZQtNLxiiUKSzhwqddrBrFZ0XhLJdrzvAt0tE3zNes=,tag:UvEbl7VlrRKorpa4yPLdbg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWXMxaVFsQzdDLzBTOTE1\nMjQyTklUdmhsNVlvblkyZGtCa2hnd0dkNlgwCnNWcXMwWDk0ZksvaXNpUlBSdElG\nRE9mSVpua0FhZnZhWnV5eGZmRnY0Z2MKLS0tIHVDSWw1OVdaU3VZTmYxcEtIaGRm\naEM1ZG01VDdGVENYNGRKRFp6aVFvK0UKWXMwTbW7ZDSiGZxIEXPzbXi29T4SjM7V\nweElfHqiCV89lkRUiGN8oXeZqgJixYNgQhvWI79D32hgv38LqtWqbQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRldSSVFlTkRvc1lXR0I4\nc25xeVFPRURZNzA3L0d0RjdIZFd2UStyMENFCnVVQzViWmo2dHo5TjloWll2ZThJ\na2tYdkJMVFlKYlY1bElCYmZqTjVUYm8KLS0tIGlqTWk4Slk0N1NDWGw4N1R0TWo5\nV200WXdxTUpWaE9yVlFuYnpVOFhnR0kKBW5o0toBgFfR7tGt8jegnU1C596QO8Uz\nEEQT0qvNwIPzFk67cXAyGYm3aEZkiUlNAJDMZYl0tx6VCOfmQJE8mg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBZ1l4bDZT\nejBBWS8zM0g4NVlFc1E5ck5Mdk0xYzBwOHBTbnZZTWplTTlIegpXNWRhQUxVSHRw\nT2V2V1AvczZqVmcrcElGeVBmM3NGQ3FIZGVMMmlYNmFvCi0tLSBkTEhvc214RGNH\nVWxjeHVtS1dFMEVabXhMSDV5NzdpWGZOV0VRMCtLZ3B3CvGNkIEXVeWQ8pNBDynG\nGqa9suEK05BK8Qq+FEYw5IyfzSCoE9CZrHR7zfxUhUYvwBjaG1KczXH4bETMXYyo\nYVs=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBK2ZjdFFw\nQzk4QXJrR3BOUnM1cDNxKzdpMHNlK1NKY1B5S3c4Y1BmU1dTWApFc3JVbDVVcGcv\nNHowbGNlRXByeWczcFFwYWE5cExnelFzQ0RER2VGL2xNCi0tLSByVkxUVmhoZitX\nZVZXQ3o0WXVWWXIzVVFmWHZBVFB0YkZKbXYxOWlhVzBBChYPmrOTu40lXKGEAjK6\ngKe9Ycp/LuRaMBKHR6D2LWpbX6NKJyDnMyTU+tQBQkN6LLuDiW/eMyVY5lGHnFV4\new4=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2"
			}
		],
		"lastmodified": "2026-07-25T21:41:44Z",
		"mac": "ENC[AES256_GCM,data:aLdlERyGcNK0BByXK0/loFdO8DVV4mTpysZ2jr9NgPm0ZOIqVpI7sRCswvFNUHOfVu6/nVPNJnbyXcCzD+611B6l+UB5dXByCXQCo52ScWaMSwad2bqwtcTQ35pm8nAAtl6tRpbxPyCHENafGQPTCeO16oNYV9qy7bvWOj7uxy0=,iv:2Y11xuLa1jQn5FQ63/PrWKg83Wlnp/JfI0fwYuDwBGY=,tag:be4d4mXgTdnPnNSNVCcb5g==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.13.1"
	}
}
