{
	"data": "ENC[AES256_GCM,data:1YEAU10hIuaQLyZa7EkM6RJGFERw6V6eEOV5HjbMxqfC4FIkHQFTbmSLJz9AYq0xnQgxUQEgXPyt2K3ofQ==,iv:QKbBuiqO4v3nW9Wu0w1p8PUd3pHmZdN1XrmwA+xiNxQ=,tag:vrSotDydUpRpLTu6Ccf3nw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaT2oyTEU0dVB6MDhWR0hv\neVd2YXU5SFp1Rll1ZExabWUyeE5EaGtZa2t3CmdZTEtvZWpEaXFmRFp4TmFMdGxw\neUJvTDdPOW9lUjZoOE0vT3VDMStwOWsKLS0tIFlEYnZDbFMrUkEwNzdmRjhlZFdn\nRDBaNzZoaU9WVDRWTVpZTXJocHZycXcKSqUxcIg2FioA+ahorabdHel5rx7aMb2c\nyrSJ9lOqvGaGss8/7Xlu014rpdLHgfbJ8uoWxYkIs6D/h4H3hp49Hg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-07-15T06:33:43Z",
		"mac": "ENC[AES256_GCM,data:xnuq/GlCCocc2ME3O1zH1D6xo576HA/9ilV2RKagDDG/dc25of/VagHP4uH0mFQznx6KXHNcIURDtASdqY3tO/3IQy8NaZVX3CasES2aPLIA2ix36RCK0UkGF1tzBylQeOS2lA3U7k9DZkpF5ei+ZEAMtoA3D0a3FurtTpcTMRM=,iv:b0QliAwwj9IG1TkXcjm9a5SE/uUK1ZNznXh4vh2Ts4g=,tag:aEqGrk/PzGZAah5HkwcS5Q==,type:str]",
		"version": "3.13.1"
	}
}
