data: ENC[AES256_GCM,data:HYOteVTlAvPnkwZcFOP2teAho/eKswRlubnfl6Cw9Uu8,iv:JMPgVrEO2b6PwIiYdP9aYgF/J8LSA2lY9kvpjM9dDKY=,tag:HCdaSud3PaSoSdgRB6ATJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTm9PUHE0R3ZYV2tBckFw
            MGYvTStuejdMSnExNXZ0VU9oUm0zaU42UFZrCjUvc3pnUWRVUXZ1azhISThaVXF2
            UFRxekxqa1dZRkJEdGtTeHo3ejVrRjAKLS0tIC9wd0Fib1RyaUlCOWc3WHh5K1lJ
            NXFHa3kvSWplMlBhVUtRdnhaalplUlUK1vRR+COK/077gONSAvu0bXBW/LmpTc/W
            HqeX51vDZQ7f9C7yteUoX0JIrT26Xw+FxDrioJ25GfJr/OSUjj7UcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1567g6raae4adh97lrfhalc9wwhmtsulh89k9pkx24m5ezfh8a4xqndrt6l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Ym56QUN4OGxZMFQ5VGJ6
            NVlrTXByQ3RHajN4OFVkK2MwQjBoa24yNkFJCk9NMFh1UFJMOTVCSXE3OVovREdp
            WmJXYllZb0doRXZGeTNlQ3BqWXZrdTgKLS0tIExqc2ppeXo0a0Fwa29nSElFOC9p
            dHYyY0Z5SWg3dWZmYUwzRm1HemhzemcKMuXlf3wSIWlJq74cUxT83YCLjH2Pc8Df
            TGZcf/XFcrAI2uqXi819FB+QE/h0h7XFbFXxkzJ/R++qkmXwNtBYIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12k7ch5r9sczu42zc6eutxtl6leudn47uv5fvsjrlq5ms0f0hz9nshm3t7q
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBMzRvSzhY
            Y0NlZXNJNng0ZEpzTFRxR1BEK1pqME54bU1GZTNLcWNrSFZzdgpWejBreDF2THBs
            aGVyMmNIUlJmYUh1K2dKRWdlWHZlbUNMVDdic2pPSThRCi0tLSB5a2hXb2RyMXFw
            bVJOS2hhdFF4WEIyaStFZnVDcE84cTZGZkd3RXFwbm9ZClz+xPzto2mjF9wXebf5
            I4Y2qTnvE/LmPd6PLuZKxEKrukvyOUfZsaKikIoKDnpElYcr5bKOwutnIvCztgHa
            LYg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBcVg1L3NC
            NW0wR09zMDVUK2ZZYW55VjgyOGM5WDFINERRRlVmSXBRMW5tcQppenc3d0Q3MUNS
            MVY4MUR5L3lDZFozZUYyTTltOTNoSWhJQWppSzRjRlhVCi0tLSBURmo2U2xNT0JZ
            Mk9xUFNld0xPWHMzSzBsR2FqekVSbXI0Tlg2bEVlV1lBCn26ljM8MH8Zv7N/tTXk
            KpNZM1LbyJkdArZ0oxKc6qpUfE7Y1fc6yGowPPZDZLY4SHJi3rWFQhQSWVeggqYC
            8Iw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-06-09T11:59:02Z"
    mac: ENC[AES256_GCM,data:pM5uhBGXxclLUXODukTdFyU3VPCRhKTRsaWZy5u8wWJ2ONJ9pp/zYLgIawePcozPrsZxJj5hiRbm/xZLW47ASey0EPHPehaqUWhvMFlXzvtxr9RtPZ7hUlBDwvb1IEYFQsFvbCmgfQgnlPbPA6ecmBHu0HKNqu8uteBgXkfc/IQ=,iv:1eOKyjQOANEljgcy28aBgMAdN+whdZhp2/ywI2lqxW0=,tag:/PgntmikF9ZZDHs0z8jfRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
