{
	"data": "ENC[AES256_GCM,data:hZU1wBeuLFQka+4gXPTCm+NsPS+KSNu+irX35nWE41Hw0eVKyynmns7qiFy11IdVVPLmaSoTF5KgppvOx5fW+NsPnIIcHLFcg+GE3bexqIbbkZW3INiaBu8Py0qp2KinghE3sUh0XvlCkadVWA==,iv:yXcx14EmrFSOFJ+ffLd6ZNh5PqnlUB+O8poFvvul8lM=,tag:1Zf1Ac8lQ5AANCos53lUjQ==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteUV1bGZJRnorcStFeGZl\nV2NuUUxrbW51QnE0a05LUEhGdzVzbUhYRHp3CkdDdm5hVTg1SWs3YnRjUnpHdk9w\nWVRHbzQ3alArNTB0ZXk5cTh1am0zODAKLS0tIFB4aTVvVTNNdHhLZzlSWmd5Y3pn\nVEg2bzBrQzhsTmdZNkEvdG9IRTZEdXcKmVh6lDjaebcOUadnunES1f3151QRvprt\nlt3wwKBmG6siY6KynPb+0/jZIABZaa11IjGsmyeoCL6hawYrwauJtA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-14T14:15:07Z",
		"mac": "ENC[AES256_GCM,data:fThkb8FgKZQQmeSsB2MBki65qmOUKrKKoPoXZFGL5eUAlsRpqH9SJEWKyoAs4jvKhSB6dVK64x7ashj4S686JSjxSOWgiKl7n/xgQmqAsR1b8GCmEF61ziqhybGyNnWeJ4BK9ltCRg67XTwcgIkbvXsLV4ZlDs8GNpMySVuHClU=,iv:MWf9x6gSFauJTT04GzwFigK1lWibkalJq7O/xaqL02c=,tag:TWU085YqcXVyn8wRCnvfVg==,type:str]",
		"version": "3.13.1"
	}
}
