{
	"data": "ENC[AES256_GCM,data:k6NVW2/jYJE5+2ONYE+FlQwSP0W99iu+Nv9AjQGZATh6pPBe2FCNhUj/dWW3utcW7M3ic1N7pEncCxNjo2cKJvFbgCL8eJxnCrrvhuGGU+QaP6FfM97JXpwY2SYUWx4aAUWIlZPgu/9uJXfE,iv:gB82tOaVm0N6p0hXXc+8GIVhvaQh4v4BoXfjur+fLOA=,tag:N59Jo+yjDnWtM0uOPy/+nQ==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M3NNc2M2WEI1L0tZeXQv\nYTJqSXdZaGZoaytvSjlJY1JITnA3TEpwb2dRCnIzeXZkNjVQVTJIOWRBY01tbHlO\nYmlJSDltVmlwMVQwNHpaVktJWE12VmcKLS0tIEE5OE4yM3UzNW43N2R6OFhMR0pa\nR25jKzJZUFNkUDB3czFWME40djhDTW8KIaHaF4HBSTfafWflV0cN9YS/ovn7Tdc6\nJGTTPnJ0b9CAkPfNd53iyZ6uJTFnCgog3Mj5syx5tcvnlUI/KJLaFg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-11T02:28:07Z",
		"mac": "ENC[AES256_GCM,data:kXaUwXIi/+l0Yme2gUNhXU1mBwF1otn5wc45b1lP3nYt2GzeS6V17DjwTsPGSvRWbvV4ULQDlntrMiTP68a+rFvru/LcDxCAJCL3EtRlmhS5RM+x/FqrI+8umh0axxsfz69vNMsk5suD+j+0pMyvzl9l608cVgdPr6uQzjxTGZE=,iv:HlA9AafqXv4UBgST9MvrXoKO4Ca1zXiSGfnSfhFg6JY=,tag:6SxuZS+BanBtiOs40//siQ==,type:str]",
		"version": "3.13.1"
	}
}
