{
	"data": "ENC[AES256_GCM,data:YUnqMIQWvvJOxu+HrwiOX8x6IOjoxg==,iv:f5izPB0+D5fwpFW7hdSak4Ex5nX6dGHxZoi/EpXMGg4=,tag:eA27Ydbx0XNbJauzK8qulQ==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1R0E5Nzc5UzZwWGF1TVRC\nUmRBWHVML1pKaURsai9Zem1pQUgwaDJ5S3dVCm9VbTU5VVdDWXNEK1BETFlpSWd5\nVWUzaVhLY21WQUdHZElMdGtrU0pBNDAKLS0tIFlqbWZBQmpkbHVtdkdXMzZLTG5u\ncHl1V0NWQlFzVEhsK0F3dVEwNzJWUHcKJs0TUH3PaA2A2Al1HpHxKZZPGtDaOlME\nBj24bEbDKvhXetHPVWwThBI9SUAYaNIaPnRivw7zZEVMbAi6zDcNfw==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:25Z",
		"mac": "ENC[AES256_GCM,data:bz1UFQhqzHgeB98BHllLB5YznaYe6DtLy01UCub+zO/ZbuBbuby/0FPQLy3zgQTHSY6h/J8fjO8voWaBS81OSTYRN7tMmc0Cau5YWTb/qEkffqFHV96vO17NVu/U+3GzjokdXmpkvDvrzPo7qDa79bejmoKpiI0nyvy23dSvVCg=,iv:wCIFNPA5jYFaokxFvMy0iSVyDLRGKKqVlmZqw/ZFFwc=,tag:mmXr3S+MATXNWBPo1Hv9lQ==,type:str]",
		"version": "3.13.1"
	}
}
