{
	"data": "ENC[AES256_GCM,data:8uiFm40mVcNp2rBkPuF+rEFA092n/ILujdF/TdMSi3mZ,iv:Q+hJOih54OCThZLoHmHMduJmHk3h+2fUA+UyEhu+3W0=,tag:Cv0tG9yBMjd+Kf3qQzkQ+A==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UHZzbG9ibklTOTk2TWZR\nOElnY0lGeHUrRkNQNFk4Y0E1SnFwejZlOWs4CmZuTm93TnBnUzVYTHJ6M3djZDU0\nalROOUdWcXlpZ0ZOcFIzNHlwWkU1L2sKLS0tIEZZL04wZm1BeWdDWXhnM2UrTGVL\neS92Z20xNzBWUTZOOUgwa2FsRHlmcm8KXHKNG+/3h1XH/Jymm8KFxGzKLc2hRqNc\nmD9CJYXr/m8arw0SBfqbMDEbQOSILRdW/D/WcPEIuXu+WDoG4rnzUw==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:29Z",
		"mac": "ENC[AES256_GCM,data:J9ATZ6wC3g8cZ6u5YU+W0gMHWz86rZ65afJF8+VGDaEp3RRjDft8q1NqfpKA+LyqO587GUDL5Hn/0FrbqCf6G8gDnAjGb2vGNrlUYvQ7g14BP88YhIRhwdXOdvIKPaXezpgciMA7sC0cULge5mQFRImwvb5stNarDdMo59TJgZA=,iv:tivacvcZrecyV7dB72g3rKTejHlf1XF2F8+Um5lsvOg=,tag:g9FbWk/MjieLnbyUMdey7w==,type:str]",
		"version": "3.13.1"
	}
}
