{
	"data": "ENC[AES256_GCM,data:C8SCaLvLNvlHro9g521S1AzuPOe6jSziD9mF+hHF0XkB19UuO15TfA9PyvI=,iv:DsmB6ynC/u7Lj1maPbI9xhiOgdVDLVDsFskgf4igh1M=,tag:duvSVxwkpbAXx58VCTfRWQ==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTejhKbzFTbEpSQW9VRk5y\nd01aeFhPemVuamVBVWVveWxnYkU3MUlvKzMwCjB6MEM2cDhzRnExQU9kaDlHVlFa\nR0lnd1pxUmtFRzdyVWMrVnhlVlFzc2sKLS0tIHE0VnNvWmJoeTlWa05RWW9VMzRV\nOWt2YW80MCtnbGVaNjU0YlN1NXMyenMK2yC98hZAAkwCiK2z+nzDkujd3+2WSz4I\nBgo/PpfcWI+K+yLmEwjCZyGuildw3ZuP/yoGND0FVtdLURVVgZ9UPA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:28Z",
		"mac": "ENC[AES256_GCM,data:iiMsACnvhcWKIJK40uQh6EsH15YlgCqLZNyciACqDfiSnHh9RwtVwHV/kUrCr+ug0skuR9XKh3hM23cEbKzhba6Hz6zynHlnzsGPCa2oS/rpPnK59KoX/5VKNOgNG/mv02klc7ZYcR7IsqfbTqlQR3rdPPPA32S6OpWhyqWECT8=,iv:QIgApwCq8iV540gjIYVApTcYK/ggq0HhX55LjAZEnLo=,tag:9ei0B/0SfICVP+ppur+/pQ==,type:str]",
		"version": "3.13.1"
	}
}
