{
	"data": "ENC[AES256_GCM,data:vNOqrSNit0++a7Lm9uQFZVMtBVmx2pR0hO5V4cnUDk+Il6f3Ptp4IHY=,iv:JBwQemUp6N7MhmDcyyLkN1bguLPyxeM+XMaw9NpPJ8I=,tag:i0ujZ5Wvmjs0EMdBdUs4iw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWFF3Q3YzKzhhMWgvbGNR\nd1lScjBnbWU0NHJDeVBJd3lubGFHTjFtcnpFCjdIRnRxZW40UkRtSFJFaEJIUFY0\ncVBKTnh6YWswWjJQa0laUjZYeUl5MGsKLS0tIHo2MnZSamxsbTVDZUJCUzlHa2Za\nSGxGOUV3Mjk3ZnBlOEVCbFIzeVNmbTAK7dd7dO7Vpj1Ed5i2aEdxqNtgeEtr2/xB\nt0vnn9AZFlutB5NyKDLIc8W8mav9zd2MMSC0GM8NW1E40H++FKx5GQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:36Z",
		"mac": "ENC[AES256_GCM,data:P65wLPW8gFJCKvgQwjLrEtDv1rgzSDYDEDy4XubFCcS0KW1yRRNXnwOfmxaz+A1V6n3mzcXixy+lTJIiEDVUJrpMqlmCr3jdgNVrALUOfLqy5P1l6fCXp0Ysz+q+AbCND/G/MdiufVSh7OKo3UgOOki1Aeo5vW0tRY4H7O7MjfY=,iv:n+rNMFfzSHiw7Gfo3cg3foG2iXofHME6Jh7Np0Tbxis=,tag:FtQ+wnVSWFiwqTC7YzbXKg==,type:str]",
		"version": "3.13.1"
	}
}
