{
	"data": "ENC[AES256_GCM,data:EqKw7ACsJLN9+tzqE960hi1IAC17ZPk5L5lV7UMSL4MsZgew5IpAUUk=,iv:BhXuCWEKTNX668z+0KVZBbg5B9vOyhIB6+GZKvQdrDE=,tag:NvEDUM4H8xKSNHvnNSJjJg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVWZRQXVJWGR1WVdWQkhh\nR1MyMHFWakhid3lIYnBUTDlwcU9QblBHdHhBCkh6bEhBbzVYM3haR0s1STdDc0ZE\nVGVpUXIrVVRoNjJHMTlFUkoxbnRUV3cKLS0tIENERjVKSXRTUlJ1SFhYbVVsYXhJ\nS1EwejBkRzUwaUlsUzJzVGJGazFEcEEKY91wpLgoNHnlmSLFssRy5fpIOUBrbvtd\n6Y7Wel+8+GJUUxxIb+OAt8O1riuS8jcmwt/VGed/BY6IO1coYj0oFQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:39Z",
		"mac": "ENC[AES256_GCM,data:NX6bIgEzfJHBsR+l1d5HP8Ji1nLDaqsVPsC8idDrK4mxL8xs33p65vZkp62zHz4DKJg4SNRbj2T/6sCcMf5FJvp7oWKW/lB2wnTgrxahpuE0R4etR+IL0PmJN8ZCwrJxSVt6hTpJN35aeOhVnCN8fuSP4aFFeYAC0rQXWqYGMU8=,iv:vewObITi1ZNMabtHBwW88wgG20fd0MZnpYnH1CT3+2c=,tag:WbXX0DMP4xGEHgUn1BLp/w==,type:str]",
		"version": "3.13.1"
	}
}
