# NVIDIA DCGM Exporter - GPU hardware error tracking (ECC, PCIe, power limits)
# Runs as podman container pulling nvidia/dcgm-exporter image
# Deployed on Zephyr, Nexus, Forge (hosts with NVIDIA GPUs)
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.services.monitoring.dcgm-exporter;
  inherit (lib) mkEnableOption mkOption types mkIf;
  port = 9401; # Different from nvidia-smi exporter on 9400
in {
  options.services.monitoring.dcgm-exporter = {
    enable = mkEnableOption "NVIDIA DCGM GPU hardware error telemetry exporter";
    listenAddress = mkOption {
      type = types.str;
      default = "127.0.0.1";
    };
  };

  config = mkIf cfg.enable {
    # Auto-enable OCI container backend for DCGM
    virtualisation.oci-containers.backend = "podman";
    virtualisation.oci-containers.containers.dcgm-exporter = {
      # Pinned to the ubuntu-based tag — the short-form distroless images
      # (4.8.3) crash with "Starting dcgm-exporter ... exit status 1" and no
      # useful log (NVIDIA/dcgm-exporter#612: distroless missing a library).
      # 4.5.2-4.8.1-ubuntu22.04 verified serving DCGM_FI_* metrics on forge
      # (both 4060s, driver 610.43.03) 2026-08-13.
      image = "docker.io/nvidia/dcgm-exporter:4.5.2-4.8.1-ubuntu22.04";
      ports = ["${cfg.listenAddress}:${toString port}:9400"];
      environment = {
        NVIDIA_VISIBLE_DEVICES = "all";
        NVIDIA_DRIVER_CAPABILITIES = "all";
      };
      # Use NVIDIA CDI instead of the legacy `--runtime=nvidia` path. The
      # NixOS toolkit generates the CDI spec and modern Podman consumes it
      # through `--device=nvidia.com/gpu=all`.
      extraOptions = [
        "--device=nvidia.com/gpu=all"
      ];
    };

    # The CDI spec is generated by the NixOS NVIDIA toolkit. Ensure the
    # container waits for that generator before Podman creates it.
    systemd.services.podman-dcgm-exporter = {
      wants = ["nvidia-container-toolkit-cdi-generator.service"];
      after = ["nvidia-container-toolkit-cdi-generator.service"];
      # 2026-08-12: podman failed with "creating idfile: open
      # /run/dcgm-exporter/ctr-id: no such file or directory" — the OCI
      # wrapper's RuntimeDirectory was missing on the running host (start-limit
      # hit after the deploy). Ensure the dir exists every start.
      serviceConfig.RuntimeDirectory = "dcgm-exporter";
    };

    # Scrape target for Prometheus (add to prometheus scrape config)
    services.prometheus.scrapeConfigs = [
      {
        job_name = "dcgm";
        static_configs = [
          {
            targets = ["${cfg.listenAddress}:${toString port}"];
            labels = {exporter = "dcgm";};
          }
        ];
      }
    ];

    # Add DCGM alert rules
    services.prometheus.ruleFiles = let
      ruleToYaml = r: ''
        - alert: ${r.alert}
          expr: ${r.expr}
          for: ${r.for}
          labels:
            severity: ${r.labels.severity}
          annotations:
            summary: "${r.annotations.summary}"
            description: "${r.annotations.description}"'';
      ruleGroup = name: alertList:
        pkgs.writeText "prom-${name}.yml" ''
                  groups:
                    - name: ${name}
                      interval: 30s
                      rules:
          ${builtins.concatStringsSep "\n" (map ruleToYaml alertList)}
        '';
    in [
      (ruleGroup "dcgm" [
        {
          alert = "GpuEccCorrectedRate";
          expr = "rate(DCGM_FI_DEV_ECC_CORRECTED[5m]) > 0.1";
          for = "5m";
          labels = {severity = "critical-paging";};
          annotations = {
            summary = "High ECC correctable rate on GPU {{ $labels.gpu }}";
            description = "ECC corrected errors exceeding 0.1/s for 5 minutes. Memory degradation possible.";
          };
        }
        {
          alert = "GpuPcieReplayCount";
          expr = "rate(DCGM_FI_DEV_PCIE_REPLAY_COUNT[5m]) > 0.5";
          for = "5m";
          labels = {severity = "critical";};
          annotations = {
            summary = "High PCIe replay count on GPU {{ $labels.gpu }}";
            description = "PCIe replay errors exceeding 0.5/s for 5 minutes. Check slot seating.";
          };
        }
      ])
    ];

    networking.firewall.allowedTCPPorts = lib.mkOptionDefault [port];
  };
}
