#ENC[AES256_GCM,data:Dzl6sEs/9WeMj9fHdlGiQvt+AM4/sjyd5Ip9jJayC7ZT3zoaFF5AWbAVtqh4K7zGVYAyBRIJ/GgTLojyhjvtVSU8yQ==,iv:lEwvygUSf3+UGFbAhvrLG/JXCqUXLA+PnADsNG7llrg=,tag:tdJXXaYLqz3iEzcn/GIpjg==,type:comment]
#ENC[AES256_GCM,data:zgh1buo0V7hxXTtq+do4LmjI+ZclAJSG68bqzRYy3w+rGlCNH6IIzUo2tSxq3cGrNz0o5OiwULf6xN4Jj4T/jp7UnA==,iv:rSmRetnMEnJ9PG4hPETKVXxkQMT7RlokY9yKaObZ4zk=,tag:D+QFSEQk+JEMH7prwq3gZw==,type:comment]
#ENC[AES256_GCM,data:bLqG2Dz+y+1hkwgT42jpo4N+ZlDcJIF04R4mn2mQQ+g3HwkmpMOPkivW199u5jg=,iv:gX7IPD06xA6dx4qF2ECvtfkTC7z/tq52aLU1D97hPg8=,tag:9cqKSp8+FPu4NKl6CGHsUQ==,type:comment]
rclone_config: ENC[AES256_GCM,data:KjlKsHBldZ5huUEBp3JGoFjKnlBS68kzKUxbsnssaFT+hpgkWzo=,iv:vSTzfc9TXkQ8gL7xLQQ8/mX5nc2oPeQy8qJWiZagmVU=,tag:6Ia23rYdFRMU4z65elzA4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlajVqM0gvTUw1Y1dDYWxR
            WS95QlR5Tmt5NkNBZkVtYzZTQ1YweThQSTNrCnI4dU1oQzROYVc1UW10eW5sY1Yx
            aWFtZzM3WXozVGlpakd4bEpER3BIYWsKLS0tIGxJMllZYjhXcGVSQjBlUmFkbDdG
            aWRoQ3Rya1JnZUFXUTUwbGJvVDQxY28K14Ue7eaV14NEJ57nRgteiivP+VIsCifC
            03v/rNiZ/pPAV9XVv0SoG2Y7P4lHQQH235WBpAqKZCH3v6HCblxZxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBN0pnVzN5
            TWdYZmEzOE84NGxVQ1VZK1kvcm5RNkFUd0dmb25vWnRuc1VqaAptZTZRUzJKWndn
            MUJ3RlNHdFQyV0ZZbkFlaEdFNDQ0L01ybGJHVTBSQU1jCi0tLSBuTmNQay9Lc05P
            dDFWVjd2Q2U0cUZQNC9SNWtlZUdGYkltZEZwTnBQQ3hFCqOWM8oR7xEP5IoygNyx
            XjKy5Cl+9Ea6JsmtkY7eAUKNgGwVBUAPLA9sGlPy6fiKZAmnkWNZPBjZ7807bNQe
            AbQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBM1dBRjZY
            NHFscjJWL3U0V2ViU3JHdTVMbHdSc2F5RFRxQy9DbzA5VTJYYgp3aGFtOHE3ZTdO
            NVpmdHNabFN3a0EyN1B0NUhRTUR0NjFqMHprS1J4KzE4Ci0tLSBKR0o2Z3duVUtz
            SDZVQXNDbUpuZHlzVTY1NWxoT3N1TWVrdUtjeE80MEY0CjeXN6uM/fP9mqkkcTx5
            usEzqcYlX8+sKfIDqLCrx/Q3kIz3Nra9U1zuA7iAUPBU7vEI2fSw+/m/VTGe69Wv
            PZI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-07-25T18:48:30Z"
    mac: ENC[AES256_GCM,data:wU1lVBVflASQ/yzFPFlMRhD1TXw6PfnhmRF5rcD7VxXPVS0TnX8/1M5UXImOYx2n8z6IPGRRUsXWKuVA64KW25BtWxkM7LlYDJUhHLzFFj2Jzl5gIwNafHaG711fqAq+gUnksJn+b69C0PBNLYblX4ugUR4F/QuG3BN3ZOcwf9M=,iv:YaAVTZ0jbFQSjEVdbr5teiIQOaMbiQZEHY+V+XXbBnA=,tag:wDpO3zElhA0Po8zzqGBp1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
