{
	"data": "ENC[AES256_GCM,data:aZNYtVW0lSd9V63pji0iLXrsOoRYkZ5klcJ1gyn2QpWqMFlULK1QtVMO4umlw76hdORc7TI70K1NeWixhZ7UHcK9FN6Hc+DF7/3od6JZ3NJ6qhYIHL7b2OxlXq8D3OCU8/J7mVrzHn5PrkEr0lXxeEsjw2SuVMURhEMWyjr8CGy1bRbVRZMwCFzqc7kT0xpL,iv:ckITzlqUZjZityfw76/qyAsod1qSutCHTQYJfUi49ss=,tag:3l4cFK9oUJP2qjgwpEtV5Q==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzS2Z2a0RGQzUrNTRVWkJh\nejNYT1JqamEyT1VqalRtODl5a1lLQTJBQ1gwCjBNK1RqZkorMzZJRXJ1UEVIdFMw\nMjUzZEVwTkNYNzJFS01ReHhwbzd2cFkKLS0tIDFXQ0t2d1VrckVhL2l2RG9pUVls\ndWg0bmE1QkhuTU9OcHpYd01pak9qU0kK35oaMURGEr6Rv/tKkxj9EYC9hEohrF0d\nQ57WYaKgKi7r9jw+dEoAwXZFmsZHCAi8FNUbYQuWCiRbnLY8OoO4FA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:38Z",
		"mac": "ENC[AES256_GCM,data:Pd2f3vo26MjWbbDFflfKTGj93fXs7Yx8C3smz7uR882nnVOkdZLx7CTkRXi1TuY/QjYwYEbG7U6kjJTHN13wgnjER9r2EeUN07sYbZ/JFRymlXIxKWE6+sqiHSCYWRRoKOPbI6YkCaAOp3zKBwSvgWj5MQVw0e40kKDHo4QmUxA=,iv:/JlW+svGfYH25edDNGCC2NaMzaDeoaOVw9PNqvw5Q3s=,tag:n057z0ATVrV2gB4EiVCBBg==,type:str]",
		"version": "3.13.1"
	}
}
