apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mining
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
  template:
    metadata:
      labels:

    spec:
      nodeName: sentry
      hostNetwork: true
      hostIPC: true

      dnsPolicy: ClusterFirstWithHostNet
      automountServiceAccountToken: false
      serviceAccountName: gpu-miner-sa
      priorityClassName: mining-low
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

      terminationGracePeriodSeconds: 30
      containers:
        image: gcr.io/distroless/static-debian12@sha256:20bc6c0bc4d625a22a8fde3e55f6515709b32055ef8fb9cfbddaa06d1760f838
        args:
        - "-o"
        - "10.1.1.120:3333"
        - "-u"
        - "sentry-cpu"
        - "--tls=false"
        - "--threads=4"
        - "--donate-level=1"
        - "--http-enabled"
        - "--http-host=0.0.0.0"
        - "--http-port=8081"


        ports:
        - containerPort: 8081
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /1/summary
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /1/summary
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: 1Gi
            cpu: 2
          limits:
            memory: 3072Mi
            cpu: 4
        securityContext:
          privileged: true
        volumeMounts:
        - name: nix
          mountPath: /nix
          subPath: nix
        - name: msr
          mountPath: /dev/cpu
        - name: hugepages
          mountPath: /dev/hugepages
        - name: sys-module-msr
          mountPath: /sys/module/msr
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: nix
        csi:
          driver: nixkube
          volumeAttributes:
      - name: msr
        hostPath:
          path: /dev/cpu
          type: Directory
      - name: hugepages
        hostPath:
          path: /dev/hugepages
          type: Directory
      - name: sys-module-msr
        hostPath:
          path: /sys/module/msr
          type: Directory
      - name: tmp
        emptyDir: {}
