# ScopeBuddy Module - Gamescope wrapper for Wayland desktop gaming
# Integrates with existing gaming.nix configuration
{
  config,
  lib,
  pkgs,
  inputs ? null,
  ...
}:
with lib; let
  cfg = config.programs.scopebuddy;
in {
  options.programs.scopebuddy = {
    enable = mkEnableOption "ScopeBuddy - gamescope wrapper for Wayland desktop gaming";

    autoDetect = {
      resolution = mkOption {
        type = types.bool;
        default = true;
        description = "Automatically detect and set display resolution";
      };

      hdr = mkOption {
        type = types.bool;
        default = true;
        description = "Automatically enable HDR if display has HDR enabled";
      };

      vrr = mkOption {
        type = types.bool;
        default = true;
        description = "Automatically enable adaptive sync if VRR is active";
      };

      refresh = mkOption {
        type = types.bool;
        default = false;
        description = "Automatically set explicit refresh rate (may conflict with VRR)";
      };

      frameLimit = mkOption {
        type = types.bool;
        default = false;
        description = "Automatically set framerate limit to monitor refresh rate";
      };
    };

    defaultArgs = mkOption {
      type = types.listOf types.str;
      default = [];
      description = "Default gamescope arguments to apply to all games";
      example = ["--expose-wayland" "--force-composition"];
    };

    environment = mkOption {
      type = types.attrsOf types.str;
      default = {};
      description = "Environment variables to set for all games";
      example = {
        DXVK_ASYNC = "1";
        __GL_SHADER_DISK_CACHE = "1";
      };
    };

    configPath = mkOption {
      type = types.str;
      default = "/home/j_kro/.config/scopebuddy/scb.conf";
      defaultText = "~/.config/scopebuddy/scb.conf";
      description = "Path to ScopeBuddy configuration file";
    };
  };

  config = mkIf cfg.enable {
    # Add ScopeBuddy package if inputs are available
    environment.systemPackages = with pkgs;
      (optionals (inputs != null && inputs ? scopebuddy) [
        inputs.scopebuddy.packages.${pkgs.stdenv.hostPlatform.system}.default
      ])
      ++ [
        # Dependencies for auto-detection
        jq
        wlr-randr
        # GNOME support (optional)
        pkgs.gnome-randr-rust or (writeShellScriptBin "gnome-randr" "echo 'gnome-randr not available'")
      ];

    # Create default ScopeBuddy configuration (system-wide)
    environment.etc."scopebuddy/scb.conf".text = ''
      # =============================================================================
      # SCOPEBUDDY SYSTEM-WIDE CONFIGURATION 
      # =============================================================================
      # This configuration applies to ALL users and games system-wide
      # Auto-generated by NixOS configuration
      # =============================================================================

      # AUTO-DETECTION SETTINGS (System-wide defaults)
      # These will be automatically applied to all games unless overridden
      SCB_AUTO_RES=${boolToString cfg.autoDetect.resolution}
      SCB_AUTO_HDR=${boolToString cfg.autoDetect.hdr}  
      SCB_AUTO_VRR=${boolToString cfg.autoDetect.vrr}
      SCB_AUTO_REFRESH=${boolToString cfg.autoDetect.refresh}
      SCB_AUTO_FRAME_LIMIT=${boolToString cfg.autoDetect.frameLimit}

      # SYSTEM-WIDE ENVIRONMENT VARIABLES
      # Applied to all games globally
      ${concatStringsSep "\n" (mapAttrsToList (k: v: "export ${k}=\"${v}\"") cfg.environment)}

      # DEFAULT GAMESCOPE ARGUMENTS
      # Applied to all games unless overridden in per-game config
      SCB_DEFAULT_ARGS="${concatStringsSep " " cfg.defaultArgs}"

      # SYSTEM-WIDE SETTINGS
      SCOPEBUDDY_GLOBAL_CONFIG="1"
      SCOPEBUDDY_SYSTEM_WIDE="1"
      SCOPEBUDDY_AUTO_APPLY="1"

      # =============================================================================  
      # USAGE INSTRUCTIONS:
      # =============================================================================  
      # 
      # STEAM INTEGRATION (Simple):
      #   Add to Steam launch options: scb -- %command%
      #   Auto-detection will apply automatically
      #
      # PER-GAME CONFIGURATION (Optional):
      #   Create ~/.config/scopebuddy/GAME_NAME.conf
      #   Override specific settings for individual games
      #
      # MULTI-MONITOR SETUP:
      #   scb -O DISPLAY_NAME -- %command%
      #   Example: scb -O DP-3 -- %command%
      #
      # COMMAND LINE USAGE:
      #   scb -- your_game_executable
      #
      # ============================================================================='';

    # Ensure config directory exists for users
    systemd.tmpfiles.rules = [
      "d /etc/scopebuddy 0755 root root - -"
    ];

    # Add system-wide environment variables for auto-detection
    # These apply to ALL users and games globally
    environment.sessionVariables =
      {
        SCB_CONFIG_PATH = cfg.configPath;
      }
      // optionalAttrs cfg.autoDetect.resolution {
        SCB_AUTO_RES = "1";
      }
      // optionalAttrs cfg.autoDetect.hdr {
        SCB_AUTO_HDR = "1";
      }
      // optionalAttrs cfg.autoDetect.vrr {
        SCB_AUTO_VRR = "1";
      }
      // optionalAttrs cfg.autoDetect.refresh {
        SCB_AUTO_REFRESH = "1";
      }
      // optionalAttrs cfg.autoDetect.frameLimit {
        SCB_AUTO_FRAME_LIMIT = "1";
      }
      // {
        # Default global settings for all users
        SCOPEBUDDY_GLOBAL_CONFIG = "1";
        SCOPEBUDDY_SYSTEM_WIDE = "1";
      };

    # Integration with existing gamescope configuration
    # Note: gamescope env is configured in gaming.nix with proper HDR settings
    # ScopeBuddy environment variables are set via environment.sessionVariables above

    # Add shell aliases for convenience
    programs.bash.shellAliases = {
      scb =
        mkIf (inputs != null && inputs ? scopebuddy)
        "${inputs.scopebuddy.packages.${pkgs.stdenv.hostPlatform.system}.default}/bin/scopebuddy";
      scopebuddy =
        mkIf (inputs != null && inputs ? scopebuddy)
        "${inputs.scopebuddy.packages.${pkgs.stdenv.hostPlatform.system}.default}/bin/scopebuddy";
    };

    programs.fish.shellAliases = {
      scb =
        mkIf (inputs != null && inputs ? scopebuddy)
        "${inputs.scopebuddy.packages.${pkgs.stdenv.hostPlatform.system}.default}/bin/scopebuddy";
      scopebuddy =
        mkIf (inputs != null && inputs ? scopebuddy)
        "${inputs.scopebuddy.packages.${pkgs.stdenv.hostPlatform.system}.default}/bin/scopebuddy";
    };

    # ============================================================================

    # Add comprehensive integration documentation
    environment.etc."scopebuddy/README.txt".text = ''
      # =============================================================================
      # SCOPEBUDDY DECLARATIVE INTEGRATION FOR NIXOS GAMING SYSTEM
      # =============================================================================

      🎯 WHAT THIS CONFIGURATION DOES:
      ✅ SYSTEM-WIDE AUTO-DETECTION: Resolution, HDR, VRR automatically applied to ALL games
      ✅ DECLARATIVE CONFIGURATION: All settings managed via NixOS configuration
      ✅ STEAM INTEGRATION: Simple 'scb -- %command%' in launch options
      ✅ PER-GAME OVERRIDES: Optional game-specific configurations
      ✅ MULTI-DESKTOP SUPPORT: KDE Plasma, GNOME, wlroots compositors

      🚀 QUICK START (SYSTEM-WIDE AUTO-DETECTION ENABLED):
      1. Deploy NixOS configuration: just switch
      2. Add to ANY Steam game launch options: scb -- %command%
      3. Launch game - auto-detection applies automatically!

      🎮 STEAM INTEGRATION EXAMPLES:
      • Basic (auto-detection enabled): scb -- %command%
      • Multi-monitor: scb -O DP-3 -- %command%
      • Manual override: SCB_AUTO_RES=0 scb -- %command% -W 1920 -H 1080

      ⚙️ DECLARATIVE CONFIGURATION OPTIONS:
      Current system-wide settings (configured in gaming.nix):
      • Auto-Detection Resolution: ${boolToString cfg.autoDetect.resolution}
      • Auto-Detection HDR: ${boolToString cfg.autoDetect.hdr}
      • Auto-Detection VRR: ${boolToString cfg.autoDetect.vrr}
      • Auto-Detection Refresh Rate: ${boolToString cfg.autoDetect.refresh}
      • Auto-Detection Frame Limit: ${boolToString cfg.autoDetect.frameLimit}

      🔧 ENVIRONMENT VARIABLES (System-wide Applied):
      ${concatStringsSep "\n" (mapAttrsToList (k: v: "• ${k} = \"${v}\"") cfg.environment)}

      📋 ADVANCED USAGE:

      PER-GAME CONFIGURATION:
      Create ~/.config/scopebuddy/GAME_NAME.conf to override system defaults:
        # Disable auto-detection for specific game
        SCB_AUTO_RES=0
        SCB_AUTO_HDR=0
        # Set custom resolution
        SCB_DEFAULT_ARGS="-W 1920 -H 1080"

      COMMAND LINE USAGE:
      • Basic: scb -- your_game_executable
      • Custom output: scb -O HDMI-1 -- your_game_executable
      • Non-gamescope HDR: SCB_AUTO_HDR=1 SCB_NOSCOPE=1 scb -- game

      🖥️ DESKTOP ENVIRONMENT SUPPORT:
      • KDE Plasma: kscreen-doctor + jq (auto-detected)
      • GNOME: gdctl or gnome-randr + jq (auto-detected)
      • Wlroots: wlr-randr + jq (auto-detected)
      • Multi-monitor: Use -O or --prefer-output flag

      🔗 INTEGRATION WITH EXISTING SETUP:
      ✅ Compatible with existing gamescope configuration in gaming.nix
      ✅ Works with GameMode optimizations (+150MHz GPU overclock)
      ✅ Integrates with Steam/Proton-GE setup
      ✅ Preserves VR/WiVRn functionality
      ✅ Maintains OpenXR and OpenComposite settings

      🛠️ TROUBLESHOOTING:
      • Gamescope not found: Included in gaming.nix, verify with 'which gamescope'
      • GPU permissions: User in 'video' and 'render' groups
      • Wayland support: Verify compositor compatibility
      • Steam issues: Check 'journalctl -u steam* --user -f'
      • Auto-detection fails: Install jq, wlr-randr (included in module)

      📍 CONFIGURATION FILES:
      • System-wide config: /etc/scopebuddy/scb.conf (this file)
      • User overrides: ~/.config/scopebuddy/scb.conf
      • Per-game configs: ~/.config/scopebuddy/GAME_NAME.conf
      • Documentation: /etc/scopebuddy/README.txt (this file)

      🔄 UPDATING CONFIGURATION:
      Modify settings in modules/gaming.nix → programs.scopebuddy section, then:
        just switch  # Apply locally
        just cluster-deploy  # Deploy to all nodes

      🎯 DECLARATIVE BENEFITS:
      ✅ No manual configuration files required
      ✅ Settings apply to all users automatically
      ✅ Git-tracked configuration changes
      ✅ Atomic system updates
      ✅ Reproducible gaming environment
    '';
  };
}
