{
  config,
  lib,
  pkgs,
  inputs ? null,
  ...
}:
with lib; let
  cfg = config.programs.scopebuddy;
  gamingCfg = config.services.gaming;

  # Resolve the upstream scopebuddy package from the flake input
  scopebuddyPkg =
    if inputs ? scopebuddy
    then inputs.scopebuddy.packages.${pkgs.stdenv.hostPlatform.system}.default
    else null;

  # Default scb.conf content — uses upstream SCB_AUTO_* env vars
  scbConfContent = ''
    # ScopeBuddy configuration — auto-generated by NixOS module
    # Docs: https://docs.bazzite.gg/Advanced/scopebuddy/

    # Auto-detect display resolution from primary output (wlr-randr for niri/hyprland)
    SCB_AUTO_RES=1

    # Auto-detect HDR capability and enable if display supports it
    SCB_AUTO_HDR=1

    # Auto-detect VRR (adaptive sync) and enable if active
    SCB_AUTO_VRR=1

    # Auto-detect refresh rate
    SCB_AUTO_REFRESH=1

    # Auto-detect frame rate limit from monitor refresh
    SCB_AUTO_FRAME_LIMIT=1
  '';
in {
  options.programs.scopebuddy = {
    enable = mkEnableOption "ScopeBuddy — gamescope wrapper with auto-detection and per-game profiles";

    package = mkOption {
      type = types.nullOr types.package;
      default = scopebuddyPkg;
      defaultText = literalExpression "inputs.scopebuddy.packages.\${pkgs.stdenv.hostPlatform.system}.default";
      description = "ScopeBuddy package (from flake input). Null if input not available.";
    };

    user = mkOption {
      type = types.str;
      default = "j_kro";
      description = "Username for whom ScopeBuddy is configured";
    };

    autoDetect = {
      resolution = mkOption {
        type = types.bool;
        default = true;
        description = "Auto-detect display resolution via wlr-randr";
      };
      hdr = mkOption {
        type = types.bool;
        default = true;
        description = "Auto-enable HDR if display supports it";
      };
      vrr = mkOption {
        type = types.bool;
        default = true;
        description = "Auto-enable adaptive sync if VRR is active";
      };
      refreshRate = mkOption {
        type = types.bool;
        default = true;
        description = "Auto-detect and set optimal refresh rate";
      };
      frameLimit = mkOption {
        type = types.bool;
        default = true;
        description = "Auto-set framerate limiter from monitor refresh rate";
      };
    };

    performance = {
      enableGameMode = mkOption {
        type = types.bool;
        default = true;
        description = "Enable GameMode integration";
      };
      mangoHud = mkOption {
        type = types.bool;
        default = true;
        description = "Ensure MangoHUD is available for games launched with ScopeBuddy";
      };
    };
  };

  config = mkIf cfg.enable (mkMerge [
    {
      assertions = [
        {
          assertion = cfg.package != null;
          message = ''
            programs.scopebuddy is enabled but the scopebuddy flake input is not available.
            Add to flake.nix inputs:
              scopebuddy.url = "github:OpenGamingCollective/ScopeBuddy";
          '';
        }
      ];

      environment.systemPackages =
        [
          cfg.package
          # Runtime deps for scopebuddy auto-detection (wlroots path)
          pkgs.jq
          pkgs.wlr-randr
        ]
        ++ optionals cfg.performance.mangoHud [pkgs.mangohud];

      # Session variables for SCB auto-detection (used by upstream scopebuddy)
      environment.sessionVariables =
        {
          SCB_CONFIG_PATH = "/home/${cfg.user}/.config/scopebuddy/scb.conf";
          SCB_PROFILES_PATH = "/home/${cfg.user}/.config/scopebuddy/profiles";
        }
        // optionalAttrs cfg.autoDetect.resolution {
          SCB_AUTO_RES = "1";
        }
        // optionalAttrs cfg.autoDetect.hdr {
          SCB_AUTO_HDR = "1";
        }
        // optionalAttrs cfg.autoDetect.vrr {
          SCB_AUTO_VRR = "1";
        }
        // optionalAttrs cfg.autoDetect.refreshRate {
          SCB_AUTO_REFRESH = "1";
        }
        // optionalAttrs cfg.autoDetect.frameLimit {
          SCB_AUTO_FRAME_LIMIT = "1";
        }
        // optionalAttrs cfg.performance.enableGameMode {
          SCB_GAMEMODE = "1";
        };

      # Create scopebuddy config directories
      systemd.tmpfiles.rules = [
        "d /home/${cfg.user}/.config/scopebuddy 0755 ${cfg.user} users -"
        "d /home/${cfg.user}/.config/scopebuddy/appid 0755 ${cfg.user} users -"
        "d /home/${cfg.user}/.config/scopebuddy/profiles 0755 ${cfg.user} users -"
        "C+ /home/${cfg.user}/.config/scopebuddy/scb.conf 0644 ${cfg.user} users ${pkgs.writeText "scb.conf" scbConfContent}"
      ];

      # Also keep a reference copy in /etc for easy reset
      environment.etc."scopebuddy/scb.conf.default".text = scbConfContent;

      # Fish aliases — scopebuddy/scb already installed in PATH via package
      programs.fish.shellAliases = {
        scb = "scopebuddy";
        scb-detect = "scopebuddy -- echo 'display detection test'";
      };
    }

    # GameMode integration (avoid duplicate with gaming.nix which also enables it)
    (mkIf (cfg.performance.enableGameMode && !gamingCfg.enable) {
      programs.gamemode = {
        enable = true;
        settings = {
          general = {
            desiredgov = "performance";
            use_systemd = true;
          };
        };
      };
    })
  ]);
}
