# Do not modify this file!  It was generated by 'nixos-generate-config'
# Zephyr: NVMe Samsung SSD 990 Pro + ADATA XPG Gammix S70
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-partlabel/disk-samsung-root";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-partlabel/disk-xpg-nix";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-partlabel/disk-xpg-nix";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/data/games" =
    { device = "/dev/disk/by-partlabel/disk-xpg-nix";
      fsType = "btrfs";
      options = [ "subvol=@games" ];
    };

  fileSystems."/data/projects" =
    { device = "/dev/disk/by-partlabel/disk-xpg-nix";
      fsType = "btrfs";
      options = [ "subvol=@projects" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-partlabel/disk-samsung-root";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/data/hermes" =
    { device = "/dev/disk/by-partlabel/disk-samsung-root";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-partlabel/disk-samsung-boot";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
