# Do not modify this file! It was generated by WSL setup.
# For krash3 (NixOS-WSL on Windows 11)
{lib, ...}: {
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # WSL uses a virtual filesystem - no physical mounts to declare
  fileSystems."/" = {
    device = "/dev/sda1";
    fsType = "ext4";
  };

  fileSystems."/mnt/wsl" = {
    device = "none";
    fsType = "tmpfs";
  };

  # Prevent hardware-configuration from overriding interface naming
  networking.useDHCP = lib.mkForce true;
}
