# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" "bcache"];
      kernelModules = [];
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];

    # Bootloader configuration - systemd-boot for UEFI
    loader = {
      systemd-boot = {
        enable = true;
      };
      efi = {
        canTouchEfiVariables = true;
      };
      timeout = lib.mkDefault 5;
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/b07258b9-b1a3-4540-ae34-69e441faba28";
      fsType = "btrfs";
      options = ["subvol=@"];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/b07258b9-b1a3-4540-ae34-69e441faba28";
      fsType = "btrfs";
      options = ["subvol=@home"];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/EB7C-E7CC";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    "/data" = {
      device = "/dev/disk/by-uuid/4c249712-3c96-44dd-bab0-0b077a168670";
      fsType = "btrfs";
    };
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/b733be92-f327-4613-9530-a5380ed77216";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
