apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: akash-services
data:
  config.yml: |2
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: provider.reverb256.ca
      service: https://akash-provider.akash-services.svc.cluster.local:8443
      originRequest:
        noTLSVerify: true
    - service: http_status:404
