apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: akash-services
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "3972d2d9cd0da4178eb03754c0862af1",
      "TunnelID": "3ae754bf-6be0-4eb8-82d9-7d9f543ef9b2",
      "TunnelName": "akash-provider-k8s-v3",
      "TunnelSecret": "qjwiYf6srLCETEV9e9zfXUmQtE9MPDN7vMoufUWqsqU="
    }
