#ENC[AES256_GCM,data:aRy9e27VluqssySU6ZUTCd52a7omYg8AMkh5BDjyE2fGe6BzC1LOGwT8irZuTt/ja+v043tke84atMGeMEDhv2sEYw==,iv:dFkHUXEb8mPxQmfkkDg7ToAe2JHmp/L6YJ63sDlSCeg=,tag:HGUH0z9uahbAlXzz3MDcYA==,type:comment]
#ENC[AES256_GCM,data:pHc9HlwouLQiz7kqFjXXzvq3d1LNfi8winSiywwJvPKCeE8z9TyKcA42VyEvabKdGa/3PohnKWFJSkt2qhpNXirljw==,iv:8QsR0TzYKcBkEq2dEJPRY3yFcj2B0dowkPeywyjTPWk=,tag:s0rDQP1apXxBDEmPcRgiLw==,type:comment]
#ENC[AES256_GCM,data:MiDNrfkvi4jZT8dhHnRS2W4jIsXoSLaJDNCu4ZaJkHHF/52f+YOcmznPN9tWRKM=,iv:/p4XRrlPFDmfmMBw3IHnlq/3/fkgrgOueVcHNTKcwKQ=,tag:KlTWTyo+QZEV5A6b0pMoYw==,type:comment]
casdoor_hermes_jwt: ENC[AES256_GCM,data:JSmPEukQtEF5hSI/uDlrpb5m4HCehhl1X/rehvn8zICMm3aFC6o=,iv:1QerLdavw9888pszoQMEdnpf30G1fC7OCOQiSSd8q1s=,tag:XYoHjgUFrsBY5e10jhm6GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMGh6MjZRWHRzcXUyWm1V
            eW5UdGJVZ0svWXZaeHFOWWhpUVdveS9lWmowCnU0L1pOL09rbVhwT0tIUDhodnkv
            MDhaTXU4R2dGYnI3VlczbmtRTCsxbDQKLS0tIElaeUVqdGdPNndLV1NmMzF0T0pG
            RWtGYmdkQmVHNm1mdGg2U3M0a1lhdDAK7EQt2GyhGKJfJm3rZxgVvY5NY2pSNEFi
            M8JZsK81gemF2UzEuOhnqWwORN+fkYXe2BRDn39FK/l72PIeFEQeoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBN3N6RzNv
            Q2FRQ0JtcVJGM3F3SHh1TXF3SDRuOURjZnhpVDZTR1IzMU51eQpyQmpyVjRGelVB
            YUJBc2F6NFpmRndEYXhNL1oydVQwOWUrUUhKMDBkbWhRCi0tLSBvRTR5RzdlVlNn
            Ny9YdndRWGNIczZkdU1qRE9yWlhrNHhPNWx0ZTZUZVJjCpn1b2XnooFsJWKd3Hxg
            JaTzARx2PLMXHJo3GdZNhZG0/CDoIDMCh/JHfKM7869y8BR9myDqILkzHtxoebJl
            /KI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBNU50aHQr
            K1NselVBdHRwSXUxcTc5UjJHcDVYN0hsUmh6b2hQWlUvbTk3OQpJVFpPZmorZDdo
            UG80OGUxYW9Nbko4MDBNUUpXUS9hYVdFNE5sSjVTKzRJCi0tLSBRQm9veE5HZ25t
            UzJ3V1AxRFVrZjFCaWx4TWhtS0NpdmphS3RlYXJqNnY4CshMsmrkmAYDRFFHKWMr
            vlh+3SjnJeGGnmKNd9s2SwquUfrnjVvJIqF5X5KtoHJ+zcRh655N09R1tJesPmpn
            DLU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-07-25T18:48:29Z"
    mac: ENC[AES256_GCM,data:myDxj/qkjsxqHsB4xwFQZCvg+LlwI5/lUXCxtfOSrRMAZyGS+zYFLAy7X82lAsiNXsJS0NdHGb+kvsgmB3UUQjdoGDEL31W29cvDFK6SzIfdEdTSQQcx/dqcrZdyx587Or0JVwa9hpO4bXJ/TpAh5FneGTKuqiwAO3wiHmAETMo=,iv:i5g0q2o5eaYMrN6HzQ6bWusf0fg3EcRB23MOYoSwmTU=,tag:ks9VgT5B64gWIrFq91GDFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
