#ENC[AES256_GCM,data:xONa7+MJyZ/SF5s6DfjdcoZzY/JQZ5jQDq/dW8lSd1HYuvP64vSINOHCcGqOEA/UHcuBGt/yDvYlir/y7MfR1jfVbg==,iv:qtibp+LTJNUiNJTXnTsgAngdtJHtLvXb7T8tjOYb3Xc=,tag:9iH1MITboAYnbZ8tgQaH+w==,type:comment]
#ENC[AES256_GCM,data:Z48rx8+HWm5GIdf4VfO7X/l59HW71rrbzBpti+Yt0/lWPDsSSph5cP1Gmr96QJmkSSskG08/NAVCVZThsQ76LPjMew==,iv:NE9P6Oex9i/K/qTVKQ8+dTXnB2flxk3TQOCg+bfa5hQ=,tag:W7hV2/SF45eF5KQDRfcEwQ==,type:comment]
#ENC[AES256_GCM,data:4utdMo39p3dKsXFNsuvrO9jU9oAkTLCWuaYvBGSExDxNTV5bg4dfp9uoANNmhEg=,iv:lC4S+v3aHarBfUhvqeoz62vXaYi3CPp6yzRr7aVPJdU=,tag:tAr5qu64ZyirOS5KPj2OGQ==,type:comment]
casdoor_maplespike_mcp_client_secret: ENC[AES256_GCM,data:qOZnN0DcPer8U6Hk5f+b9OCV6mytkCMSGC6zdE8XcCmKQbFYjz8=,iv:0pL9GGBBd/bKFFR43CFixUOEbqB5XDN01yc/QgbpTyw=,tag:bbgwT1g/Wm4fflMqIgnOmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUmgxb1Y0MWcrTkV0MXlN
            dlROa2x2SmMyT1dSWkxXSS9kNG1yVnNuTlRZCkdxbERRK083MmMxSUdRVDAzQzRt
            bS8veUFreHV3RGwyd09VeWpITkJKdjgKLS0tIDRKQnUzR0tldWZtVTd2ZjEvTlVL
            aTd4ZDdtUURjRHo3SjlnRktwTjhTdE0KCBDq8Tz9i8b7d1InBZdkeDhIHDQKRNKJ
            CkIZ8pHJLKjOQ89sU9yfIThlkCwumRxKc2rxwjRYSZmHhhH7jLLQBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TDZJcnFVNGJuWUUvVlFP
            SnMvRXFJSTZLM0ZqWStoelowUVBST3BSQWdNCk5XNUlneDE0VFBHb3p6MERXZTZV
            cHRUUXNZajVpTkxBVkl5MnRaTjVBa3MKLS0tIEZvY0VqZzRzS2R0dFZheE5HdEVJ
            b0Zobk5EN1ZvTlI0ME1OejhHRVhmSzAKAUDfKldiO2Q1j/aFjCR3Ug6n3Llgh0uB
            m52Us+HETX8s/8PQGfrWdW8pKFgGjoxf8Twcpv85uP94ahAYPGFkrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBclBDY1Rt
            TUY0WVZkSnJrb2VveXZVR0d4cTJ5L2ppVkMzb2xoQXhRZkN1QwovVmMycEthQTJm
            WDRXQWNNaTB2eFRrakEyTk9vNnBTd0FmcndSRG05ZWI0Ci0tLSBWdEZicnlJekJO
            UVBNeDJPbmlrdGY1c3hOOEpvZXUybTk1R2ZTNGtqQ0k0CrXVHXGLUdOXXXK4dnSZ
            5PaD7cHKyoIz9jYf5Ik4dPej2ksVF7seugxe8QdjiBD2yggL+/ViXpzD7cP+tYpR
            x9g=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBdEVKcXRH
            cEQrd3VKUkV0cUZRTHVqd0RGQ2V1L0J3aFB0aHV6TUE5SlI1RApWTFFLeEpuUlBu
            aTUxTG1tTncvYWtzcmZOclJJQTlQNTgyUnV1K09lUko0Ci0tLSBZTXc3NVVlQW5C
            WkR5OXZ0Zkx4V0JSM285Q0p1RFFScXdEWnc1bFh2T0dNCp+bQGeIeFZeqjRpcYS8
            8xtuE/QBSAy3GzxDctWgGNQxOeeFTM1HFsXZb1BanSc/x59Dyre8s+phNNZgLy+k
            wAw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-07-25T18:48:29Z"
    mac: ENC[AES256_GCM,data:YnA+SJftyk2cjIctSoIUgpg4L/Nz/ceChcW9SJYD69j9S6DcEJzMbGOOCda4c4GXAf3F17qOYncx3+7oAD6apilkZdhJp1MqzpanyaSoZlIF1iEjILCloKpA6pvKvAwbPdf6HhEdXl9EkQdqvMsuef5Uy5Mbzgj1kj8w7sUDThw=,iv:aAL8cL4OnP4bIvPSeNukT3O7jGXegSN1UwSsEKRfldM=,tag:0vbxZejkHAIGiGOv8V4+xA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
