#ENC[AES256_GCM,data:oG7kqFKXOrsHD6q2R3cHImdWyWd7g5JQC+qO9cTsPgeD/9L+V92ZxB/fERF9HI1an4XoN8dw65O6QJ0Y1/HHO76law==,iv:ubinOTATngb/WWtqlAPOqdcaa3LYQsmofCu4bHKlbrc=,tag:oAemAAswKI4ySP7uFkzkAw==,type:comment]
#ENC[AES256_GCM,data:mpM/CXuIWkEJ4/qMqNsHaLPcquJmvZNMTdYyNSTKdTqy79q+YJHWY9Eam/TV7dC5gT/+UzAaae1K8MokhIt+f4JN5g==,iv:N4g/v5Zo5EhzsQfoFukcE2lt+6SqNlCOVPbjPNNBqRY=,tag:JsNbSEmr4v4Z0PA6JfX+/w==,type:comment]
#ENC[AES256_GCM,data:YYxkmOBFdjnq2lkwOPUSMURt+cLYc96S27/B5WRudYefXZtn8RmLm9jG9ZU75nY=,iv:JNMjLSnIX7FQa49RIYJlmH9j76As0XDQKRuU6uHKfnk=,tag:M0xiBo+yZvNS305qk/Fs5g==,type:comment]
casdoor_maplespike_api_client_secret: ENC[AES256_GCM,data:m2UZzjm+arf1BqWSwsK4mP9CvAcMOtKO4UAQMI+RdAydVbdLVVw=,iv:Sv/lY47Hry/LQdSILjcJ6wyae0eqZVHZgVIK3InoXo0=,tag:mqqBhjWinLBLQijwfFmaSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R081Q04wNVF2SHdDalVK
            VzJtVmRLUGRnM2RqMXJTSmt3RSt0Z1ZIbmhNCjJVN2g2SjN5L3k0MWwxU2ptbTFQ
            elhueHN3YjBsQk1SNnJWN3B1c1pGYWcKLS0tIFQzajRjQU9wVWc0cFpLSDdMdFhk
            UjdwTldEK0RNYzNKMWJZTHcvT0FReEkKWpIiLTE3p5bJfyx70ayxmdz/GSR9uejO
            TTwyJfarHdhGUmhnMG0xct9kYZtYwfSQrUAZJ88kiqTSmBPi9SAICQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBNFZzdXdI
            MEdrWStpcUhab0orMFIyemZTRS9iMTJmQkduMEkyV3NldzBxLwpIaVgvUDRmS2w4
            eDZpWURYdmJUZ3VjOFJ2TlU1djhxMnlIb1J0YXJTUGpNCi0tLSAvYU5rMXNLS3pr
            dVpiRSthcjNWNVc4NlNzd0JicG40MTlDeVN5NEJIUFZFCqVVwGANpmyEXg5j4qKe
            E+0+M81GgAOmIsb0eVBeqF2ggICOM1EUIIU9VpjDQbdIbUY/QPtJ+H6577b2JuTR
            gig=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBb2U0RVdC
            NjRHb2dSdHFjRy9XdHRURlB4Y0lFS3A4aTBYazRpSEt3OFhadwppaE9ET250cUZN
            QnNrMHo1blFmTDZTblRqZGJlWkNUM1dnbGtSZ3hLbmJnCi0tLSBTYXdkb1Z3dWEv
            clZNSUNzUEREL1BnZGtSRXBCNkJpc1dUcnR0YzdTeHU4ClBFcj4CtYRp0ozvuOZV
            nenThTQxdE9paE6Tv31v2eblV7ZvWldID8iL59hrzCckoHszdf1v6eGbLFmYKsfs
            ouY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-07-25T18:48:29Z"
    mac: ENC[AES256_GCM,data:pCkOw7PtqhfqeCqn0sEXn0C6HUph965mhMmdmAFq6aX0lhyC4uOC+/jrAqx7Dyn/iCaO0hgHtUAUGxCvckSXxcc/A7M7kAyVsJv/XoksBVhdLGV/GfA4aTb2PfYcJ/X8L2QBMVk+PDlfZbpP5LCxuYi3RclAvVRPUoz6OssmW0c=,iv:d60y5iB0jk5py7qaHsgQ7+lZwMwr5TL2eW6Iow014UU=,tag:fjQDhDfJAiizFcqw7vfOAw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
