#ENC[AES256_GCM,data:1Erf82w/R0RFT07WwEt9EVb/jvSsyF+zdXPWvR8KiV7SZ+5fLtR2fkSjoOofe7gAoLz6eamJ+FmVxBU1NfGeHFlKhg==,iv:LNywvuykg/E5lIl2wSAoezIsFruPTqDOTr8nxDdjJ1g=,tag:mrWSA0diIOpdwTbEtR6wpA==,type:comment]
#ENC[AES256_GCM,data:I8k0/iVm8nlASibmyGkFHkMiac9fR0AWXv4MWKlskYlj3IqblMEtnMjL6dHdFSOFDMbN4w5YakPSZ82T7HQitCK1IQ==,iv:eiAHkSqJp5SXjagjzMgM7PlcQMZjrtSb/gadBcaQE6o=,tag:BcnYtkSnp3JbkAQ+bMdxhg==,type:comment]
#ENC[AES256_GCM,data:UpsAgqJ++38CZLfe4XuvGRBcL8OJ/VZ5XYyPugyXcTVZEY8bqMWTA0RdnIA5OwM=,iv:wJqkVmzZMmN+jUx4K+vQY7DuGswWojYFrbPD2Cnh4P8=,tag:LXhQD95LarKZTQu5dmEHvg==,type:comment]
central_auth_cookie_secret: ENC[AES256_GCM,data:nE2zFTDIw9NLs3rjXrS9bFBWpHjZFVXGklkQLApHD5Gm0uZJPyY=,iv:bL66Rs2ZMSyo8FSGuLBApeCxMPc0L0rFChqrIRNRVvs=,tag:5WjYB4h4psjB+XcF7f6MHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c3U2MXFubXBBOXZCSzRn
            UkdiOVlmUGt0aXhsSzhsaDJORERIcm1pQ1VJCnFjUSsrcldmZHlGVUpQeHdDZnND
            K1laUlJOMDdEMlNWTG5vRHp2MWViQkUKLS0tIDNTRnlLV0dhSUdZWDZTZTlFWUtC
            aTNVRkVpdTNqbE5id0VHQlIvc2lhTFkKhf6/5KS2LJGe67AMF0epz8Bmb8qWookX
            lvxyt9pAlrybxSonDspq0OFcWHM1SM+ztciU+rdkjJm9FMLkOiYexQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBcUtvRUFi
            VzdCQWlsNGxYR3BudWtpM1VEY3J2UFlLN3p6bFRwUWlxc2FHVQpHbklxajdUSmFx
            Nno4c1ozWEVINVlyNXlueVZQbW9VejVTNzROU1phdjVvCi0tLSBRemQrY3pCM3hz
            bGpFYVZlUVhvb3hpYS9ySEh0OWxHWjB2TlJIZVdsWmNZCsuGwhcPTctoERfv+XE/
            vfouC8n97tm3IgYjGX6AWVMA2hdO41zhylLcPb34UciF74/wHMhzhbwoAoolLk05
            +zU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBd3lndENF
            T2VwODlaUFFhQUsybk43c2didUFIR1hoVFV0NUdYMVNXdmNzeAp4NEFyMWdwT1hx
            SkUvYUpCSzhrUUNvdGFjQ0Q1VUpMRk40b2VndnV1SmhjCi0tLSBYQWtVWnNqMElD
            RTU5aXQzVlJYbzNnbUtlNHRDSmprM3k5bnBjZFVYd3BZCkMpDo5xvXoEm67ZPK89
            gT35X2vyAeSx3VSQuB8Jhd3CXotLuCqRwhG7WOBdhBhkZ4LCpqVqbLgm8Jm9RtJ/
            h74=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-07-25T18:48:29Z"
    mac: ENC[AES256_GCM,data:6iXi/JeYJiT+RPml+VGHZBtZEE/pUU1GkM8V4Nwo07AZ1O/uFZ6OQv4Je6cMfE2m9tZRPMaYz0fWagjFrUnhJ5rySFryUvwzM+hQGeRJQZxzpmIFU+Q2J3uDxDwRN4VFRsVEBhd9ybDNibyZyYPPAS/8m7AEeuHx2VxpokOfoOo=,iv:haCFHcru3fZ1fGlAqGJTFArN7gQyiKGDT3CIxpMbGEc=,tag:UdCZ2RAgX+51tSqFIaxzhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
