#ENC[AES256_GCM,data:J7NDp0jC0ulaWvUcVwUUbzod5o3DJ9favzqtOq+C0gWMZ84tiA8YwAQBNuV00bl5rmgSCgTs5FtXOIdLKndXHJ3Oww==,iv:o0qyWbRX31e7LH03U9nCq0hxuqGMPhstBGDtIbjZLwY=,tag:OKMNm0da4S/LQe3pZ+TYvw==,type:comment]
#ENC[AES256_GCM,data:Gx3DmTNZdk/tl2PmQndzCrjWm0NmCtgmvEJXs4ne4obLFXoV6V3sAOyavr3ODZoN7oXs3J/5MYBDFRXJtwa+uS5QCw==,iv:qZSuNpPNKQ0QGTmBH+dNgrWMfsYG2kq6TnJ9imppfTo=,tag:C3oV4YXYX9X38K6IpXH+Qg==,type:comment]
#ENC[AES256_GCM,data:5LU/3+OMcMeIbTeLN/8r9XBJr/a8FmzKxO9q0JoUqxqosa1nbOdItwGOamSi4pI=,iv:UQz9VIP9RiJCdW/vEAngfuhAIenXkZ27aoUCB9IwUrI=,tag:gwnRw/ZzbFqX5S5iicMV3Q==,type:comment]
k3s_cluster_token: ENC[AES256_GCM,data:iXIOIS0S2jJULzK4k5HmFLre4IfNvJDXg8c5W3I9DAOU+wIUQaQ=,iv:wTd/qLdh5vgLUx+WDcbZNnC+V2Kun3MDVVFtGokZG5s=,tag:p5m77YQeLFfC3xsJ0K3oow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SXJSWG1xcnVlRkxuMCth
            U0ZIUGFDTGdCY0REMjNuOENFVDVmYmRXUkZJCjZ0WVV0UFUrOEpLdW4wZllzTjNi
            WTFCMmpBWEdIdkNUeFhSWURKR0J3Y3cKLS0tIDNSck5QbnlRN0RqOUh5VVVDbGNs
            Qk4zNjJIdndmMFd3VVNLaitid0oveTAKUcX5yEZelsf+k4sUyzfBDZYSS+wejzk1
            OrUFxJwQA7LQ9wE2LoMb7pEaSMWOLFpkXrgsfVYij6dnJqiLCtAtQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBdEpCU0Qx
            TW1FVGJhUVVYTHZ0NkNXQmM1VW1UdUpBSlJ6YVdmSDV6dmxvawpEL1BwVDQyODM4
            T3lHZ3JxeWtsOXVXSGZLcCtYMnVZM3NHblVpTVNNbnVjCi0tLSBpMDNBa0F5Mjdo
            TkZYaENFbks3RlhoSGhVWlFyRjhuMzY5QjZpTjc1MmVBChlQWoGQP4qyVpCPjpNd
            cKOhTahTNSgkdZKAZAeGpGiJv+kMIn30U2nS3MQ8zDM54EsgWu36NnyTkG1PlljN
            AYY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBZ2s2Qkdq
            WGJreVl6QTVwYno1R1RhNVUra1pCZ1h5T3RUMXJoeXZTaEZDZQpLN3FDK3Z0TmZs
            RFIyZTlucms4aHd4c2prZHkyT0hKVkZLUkcxMitzMDZZCi0tLSBaaUV1bmJZa1Mz
            U3Z1S0JiZHV6RjVVVEdVMDdDTUEzUHNPY1lERExKcENnCu7IoA7vcKKsLCyxgcXI
            KhLlE2s1eJKBkMF+i6B7mbUTPrsno+azJ+hrMclkIqZws6+uAi4hdDLfZn+kmXtW
            Z20=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-07-25T18:48:29Z"
    mac: ENC[AES256_GCM,data:Qb9m3pj0EC0OsCenkka2YINIF3ymHK0b49/gkDkoL96lZGNX/9dmape31c5r01UFT2EpybHf6W809HvfjChjbdFZxvnmcvERe4GDPMokBowjxBTAtgsx+J2ENw1QWWSTApQvogMJDwDUp0KiCrglO42qUpfX6xQ8ipqJRDOS7PU=,iv:9iIqTk16WNcuj/jkzDg/eP5hV6jV5sIzfQoQqNWgm3I=,tag:zoluzYsfBDhIbXaZIAmWDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
