#ENC[AES256_GCM,data:RDTJC6dn847Mu4DpBAQd777f9xz8R3MB4dsauB6fh8iGDUQZKdEz0CkxPLg9WNvgQMPHUB/S2wYaVYAvkkCEnpqIcQ==,iv:DLjZNL4nBDGEk07Z8RJf+gZPSwLOyFZNKg8lJCMNTW8=,tag:TT9D3M7blMKahDgAtfRcNQ==,type:comment]
#ENC[AES256_GCM,data:KUzx5E1zfELDbXPOkCE76DfY8bcUFj46R7JHquoVOgkPG7rdLi1D58glPf1S3Q6c/XunbQx/cPvnZUEfbFW+vyJ1+Q==,iv:GpbUTEViwRk0qtVL392MTnO/bDyV93apw0J6NH/1HFU=,tag:5+Weyy+AdLi8WdvcV/jjLQ==,type:comment]
#ENC[AES256_GCM,data:mIzK5ggy4ZcpI3uA5pLD7mhHof9GNXEJ072nHN09+v9Pq1HZ08iA9WzKxWOhLVQ=,iv:eU/Ya3oE6LxoQJPbjyhbLr/djVkHXbzaGKbB8dHKWao=,tag:QMLDIdu+o3N6PoDaenczZQ==,type:comment]
openwebui_oidc_client_secret: ENC[AES256_GCM,data:GZJOmAhHWYLemlildJ1n6oCr21wQxvzAvq/A8l9bU/qbBb/88Xw=,iv:TvXTNTYnmqZRaLzTvbt3wN6/OcuBpf5SpWQRp86pOPc=,tag:t5xK/U4mgqQEQl6mA0q+Eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RFdwZDVISzNHSjJvRDE4
            MERScmZMWXEyMTViTnlqRFBCVlNLeUhRQnk4CnpKZXl1aWJieS95YW5sVE9MTXgy
            am5hMlFyQkhPQ1R1YzIrNXdlVk9uaFEKLS0tIEVBWnZ2ZGQvdWNvbmhVS0Mxa2ZY
            U0RPb3hxZDRBQmpzcUFqdENqSjB0OWMKJ/4CPw0E6S4t4yhf9fIOnsqekX6xslPu
            cu6mLe9ydeL2XXwFXhdH+SZMNNnV+gnk5+RSzy+iAgPC/Nf551m/Rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBbGtsbHEr
            cFhIL2dXU1dkNU5GMnVibFJnaCtJbldhcHJRMk41a0lVTE1LRgo2SjN1Ym1SRUhi
            QnRaTGxPekYvM001aHY3K2U1L0R4bndGVDFsNTMwWVZ3Ci0tLSAxb1BwRmVjMmFJ
            ZGlQaGZpMnUyWjliMkFGenluaWh6d1VsNU5pYVpsSURZCsFLps/q8c++9eisZZ5q
            JJGoTmgvs1VO2MeJKDMI7D02/oUmnT/vhOxt4ihgvYQphWdf4bnPwQKUoxckhzMf
            zE0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBOHFwaUx6
            U2cxdHlpYzFYRE5qcXU2M0JCZ1hTR2h2alF0S29sZ2daRXhuQwpneG43djdmNGtQ
            QUh2MFdmNklFMVhDRHg5czBNTlBEK3MxY2p5dlJGQVk0Ci0tLSB6MUdYN0tqTkZR
            S0hmQlIyYzdFUTdEd0RYT25kdTVGdWluR09OSnRSZzBjCukxVkpmC5HmyQbM6Ock
            wXRIdksC5sRlIsq4/lDJZqppCrPYVaH2BqJbDYSkFK3h9tTMBmv3PeHylaFn/0xY
            7Uo=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-07-25T18:48:29Z"
    mac: ENC[AES256_GCM,data:vr36GtANS+M2Z06v2DTU5n1upEhjESbkAZvJG1Oc2XdDw2FXKLkSoKQ7zsbYYTC4N/M/wesxTD2y54ku3pHdSaBGnulaY5SlbEjCUZ5mVNXFhgzOXel/3iu/NDp9XAujSEqYrW7pdMFNMEF/9nfnflxOI77/hNUM1r0BWDmDkAQ=,iv:EHpv2NagiJPtB0ugKOQecjmeC6yjdNKUQY0jcv10Xl8=,tag:H0qt64ejkOpPDVF//QWKGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
