#ENC[AES256_GCM,data:eqD4hOvRo3DBtJ9bDRTuqOq7WZam8hRYQ1uhzRX0tapzJsigr5Shq/UNFFy8UlzUvQVanKis/rbui1POIfro/VcS4Q==,iv:yY0vYrPTIE8CcB3UnekUfqjTssaQdxC6qvGhAD4rjIY=,tag:iPNeSFEsVIaoGDSES7JGsQ==,type:comment]
#ENC[AES256_GCM,data:nMimvVvqWn21OrH5x6djewH3yrtHuBA67dBh4wKNGoINr0hGCGgACBnUiOWVbIuYH46yWB6dm46a1cOMQ1NJgz6MfQ==,iv:xGNaolUMZj+wByB4f4h/6qHtOS4Q2FUsyGYyelq2604=,tag:lFbVNr+km8K8VwzNBCM2IA==,type:comment]
#ENC[AES256_GCM,data:WpcFnQPPEXpMIRkYEHQgcoH54u8Y5WGS126T2o44BPSjYAkmmzZvdImF9xZidWQ=,iv:qgf386npgzzfy/voA3e1q4mHHUbXAbraxx+J3vZBa1M=,tag:zfsmd2KXLseUoQv4PTmMcg==,type:comment]
searxng_secret_key: ENC[AES256_GCM,data:20AczGhtBq3FurXTWLISUyUzdVLy8uSQdj2SPHcIjVLwTgNlhPs=,iv:/03RrgRt5kK0T3Hi/ux76V4oYM0qmRE+hjYqA9gG0fk=,tag:dKziph7Yj6zLZlKLXeG47A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR1pKeE1zdi9JSXZ0UE9j
            cUp5UCtNUWJ6cUFYT2RNaW1UYVJxdGxGczNZCk5mRG5IOEM5U0ttUlM3dm1LUDhm
            cjN1b3dCMm5LbDVaOC84Z2xuOHVpaFUKLS0tIEwxVHkwSllRWDNMZ3RJQ2VZZWF4
            anZLaU9nZVJoelRHTUZEME80L3JtZWsKxQ3CyL/m0MstxL7vsuThsWITCufI1gU6
            UOD0L+x1cLncgHSN3feCXgF4JhcdNQgM7OP95sG5vXiHzE/0LzRjZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBa0hqT1lr
            Y1ZYbXhNUlNCTHh0eldYSlgyQ0VmN1lEZWxiSnFOU2FIUnRjaApPT2lyeUtVOSsx
            OUJGd0YwbXhOOUUwblZnZ1lsRzZqdElUQjlHVno1QnlJCi0tLSBpWmFWVzBlTGho
            KytCSGZWYjdjd0ZkcS9SaElBUzVvM01QN2JEOW5va0h3CnkzMP0TvbXZHsjkgqAP
            XFvHauDFlqprdHE2UxNUC/9zZf0QKE2R6ubf0SFSsPy2LidVeHv9NS95bsojL1fq
            sJM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBZzdsZHB4
            OUpmZVN2SFNHaGY5MUVPYkVOSE1YOC9Ha2o4V2NHVEJhMkFjegpicmlsamh1ckV6
            K0FnblI5WWVVU3Ivc1NOY05hRVZwWVVNVkRsSEZPVjl3Ci0tLSBnZGR5L0lPN05Z
            aE1MM3I2ajQvUXRxUWV0SHFlSUZXMzJQV3haRXI1Zk44Ci+yC76rvf5vdejWQML6
            Cj8zAEXnJ/ysWPD1krh4j7+WZRFZhN49ffEjoVlG/qKzr0Uqvnqc5O3/0XiDoZxx
            40M=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-07-25T18:48:30Z"
    mac: ENC[AES256_GCM,data:jQ1icJ6fEbe+SwkW0PQhi334J2oD58MQg9rDeXx9uA13BdatDGn9DWML/ux2ZoAjlnIV/RoVywSER1sEXukgRXoa/24d4oHBVvOsdFcvFMXz8wnssukNWo0Zpe8HOD+JihGF2y+5fpcQgHtWKjGts3aSWanou8BfhrRXqnqNXs4=,iv:tMvpRVUIhCVfYGLLtu2VoZZBVBr8Z9/DtN9TXTULACM=,tag:ZPjivMIfkOpvhRrFcfYAxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
