apiVersion: v1
kind: Pod
metadata:
  namespace: mining
spec:
  nodeName: forge
  containers:
  - name: debug
    imagePullPolicy: Never
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev
      mountPath: /dev
  volumes:
  - name: dev
    hostPath:
      path: /dev
  restartPolicy: Never
