# Do not modify this file!  It was generated by `nixos-generate-config`
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
      kernelModules = [];
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-partlabel/disk-nvme1n1-root";
    fsType = "btrfs";
    options = ["subvol=@root" "compress=zstd:3" "ssd" "discard=async" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-partlabel/disk-nvme1n1-root";
    fsType = "btrfs";
    neededForBoot = true;
    options = ["subvol=@nix" "compress=zstd:3" "ssd" "discard=async" "noatime" "x-initrd.mount"];
  };

  fileSystems."/persistent" = {
    device = "/dev/disk/by-partlabel/disk-nvme1n1-root";
    fsType = "btrfs";
    options = ["subvol=@persistent" "compress=zstd:3" "ssd" "discard=async" "noatime" "x-initrd.mount"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/disk-nvme1n1-ESP";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/nexus-storage";
    fsType = "btrfs";
    options = ["subvol=home" "compress=zstd:3" "ssd" "discard=async"];
  };

  swapDevices = [
    {device = "/dev/disk/by-partlabel/disk-nvme1n1-swap";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
