#!/usr/bin/env bash
#
# Setup OpenCode Environment
# Ensures local or configured API keys are available in the user environment.

set -euo pipefail

LM_STUDIO_API_KEY_FILE="/run/agenix/lm-studio-api-key"
POLLINATIONS_API_KEY_FILE="/run/agenix/pollinations-api-key"
USER_ENV_FILE="/home/j_kro/.bashrc.d/opencode-gateway.sh"
FISH_ENV_FILE="/home/j_kro/.config/fish/conf.d/opencode-gateway.fish"

echo "Setting up OpenCode environment..."

if [[ ! -f "$LM_STUDIO_API_KEY_FILE" ]] && [[ ! -f "$POLLINATIONS_API_KEY_FILE" ]]; then
    echo "ERROR: No configured OpenCode API key files found"
    echo "  Checked: $LM_STUDIO_API_KEY_FILE, $POLLINATIONS_API_KEY_FILE"
    exit 1
fi

echo "Available API keys:"
[[ -f "$LM_STUDIO_API_KEY_FILE" ]] && echo "  ✓ LM Studio API key"
[[ -f "$POLLINATIONS_API_KEY_FILE" ]] && echo "  ✓ Pollinations API key"

mkdir -p "$(dirname "$USER_ENV_FILE")"
cat > "$USER_ENV_FILE" <<'EOF'
# OpenCode Gateway Environment
# Auto-generated by setup-opencode-env.sh

if [[ -f /run/agenix/lm-studio-api-key ]]; then
    export LM_STUDIO_API_KEY="$(cat /run/agenix/lm-studio-api-key)"
fi

if [[ -f /run/agenix/pollinations-api-key ]]; then
    export POLLINATIONS_API_KEY="$(cat /run/agenix/pollinations-api-key)"
fi

if [[ -d /etc/nixos/scripts ]]; then
    export PATH="/etc/nixos/scripts:$PATH"
fi
EOF

echo "✓ Created bash environment file: $USER_ENV_FILE"

mkdir -p "$(dirname "$FISH_ENV_FILE")"
cat > "$FISH_ENV_FILE" <<'EOF'
# OpenCode Gateway Environment
# Auto-generated by setup-opencode-env.sh

if test -f /run/agenix/lm-studio-api-key
    set -gx LM_STUDIO_API_KEY (cat /run/agenix/lm-studio-api-key)
end

if test -f /run/agenix/pollinations-api-key
    set -gx POLLINATIONS_API_KEY (cat /run/agenix/pollinations-api-key)
end

if test -d /etc/nixos/scripts
    set -gx PATH /etc/nixos/scripts $PATH
end
EOF

echo "✓ Created fish environment file: $FISH_ENV_FILE"

if [[ -n "$BASH_VERSION" ]]; then
    # shellcheck source=/dev/null disable=SC1091
    source "$USER_ENV_FILE" 2>/dev/null || true
    echo "✓ Sourced environment for current bash session"
fi

echo
echo "Environment setup complete."
echo "Source $USER_ENV_FILE to load it in the current shell."
echo "Test the gateway with: opencode-status"
