apiVersion: v1
kind: PersistentVolume
metadata:
  name: akash-provider-nexus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: akash-provider-local-storage
  hostPath:
    path: /data/k8s-local/akash-provider-nexus
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nexus
