# Do not modify this file! It was generated by WSL setup.
# For krash3-krash (NixOS-WSL on Windows 11 — krash user)
{lib, ...}: {
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # WSL uses a virtual filesystem - no physical mounts to declare
  fileSystems."/" = {
    device = "/dev/sdd";
    fsType = "ext4";
  };

  # Prevent hardware-configuration from overriding interface naming
  networking.useDHCP = lib.mkForce true;
}
