apiVersion: v1
kind: Secret
metadata:
  name: mission-control-secrets
  namespace: orchestration
type: Opaque
stringData:
  auth-pass: "yt1x6F61dfy6R9jpW66q7zgOLdnbNSxW"
  api-key: "5MDMlvnW0gYdgZxk1y6PZSuULQRpIVxw0OxSPqZHm8o"
