---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mosaic-bridge-buzz"
  namespace: "orchestration"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mosaic-bridge-buzz"
  template:
    metadata:
      labels:
        app: "mosaic-bridge-buzz"
    spec:
      initContainers: []

      containers:
        -
          name: "bridge"
          image: "nexus:5000/mosaic-bridges:v0.1.0"
          imagePullPolicy: "IfNotPresent"
          env:
            -
              name: "MIS_URL"
              value: "http://mosaic-identity:8081"
            -
              name: "BRIDGE_TYPE"
              value: "buzz"
            -
              name: "BUZZ_RELAY_URL"
              value: "wss://relay.damus.io"
          securityContext:
            runAsUser: 100
            runAsGroup: 101
            runAsNonRoot: true
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
