{ config, lib, pkgs, ... }:
let
  inherit (lib) mkIf mkBefore mkDefault;
  clusterCfg = config.networking.cluster;
  # Get DNS config - use or {} for safety in case the option doesn't exist
  dnsCfg = clusterCfg.dns or { enable = false; };
in
{
  config = mkIf dnsCfg.enable {
    # Disable systemd-resolved (conflicts with unbound)
    services.resolved.enable = mkDefault false;

    # Configure unbound
    services.unbound = {
      enable = true;

      settings = {
        server = {
          # Listen on localhost and cluster IP
          interface = [
            "127.0.0.1"
            (if dnsCfg ? listenAddress && dnsCfg.listenAddress or "" != ""
              then dnsCfg.listenAddress
              else clusterCfg.hosts.${clusterCfg.hostName}.ip)
          ];

          # Allow queries from cluster network
          access-control = [
            "127.0.0.0/8 allow"
            "10.1.1.0/24 allow"
            "10.244.0.0/16 allow"
            "::1 allow"
            "fd00::/8 allow"
          ];

          # Performance tuning
          num-threads = 4;
          msg-cache-size = "128m";
          rrset-cache-size = "128m";

          # Privacy and security
          hide-identity = true;
          hide-version = true;
          tls-cert-bundle = "/etc/ssl/certs/ca-bundle.crt";

          # Include local DNS records
          include = [ "/etc/unbound/local-dns.conf" ];

          # Don't query localhost (prevent loops)
          do-not-query-localhost = true;
        };

        # Forward zones
        forward-zone = [
          # Tailscale DNS
          {
            name = "ts.net.";
            forward-addr = [
              "100.100.100.100"
              "fd7a:115c:a1e0::53"
            ];
          }
          # Everything else: use upstream DoT
          {
            name = ".";
            forward-addr = dnsCfg.upstreamServers;
            forward-tls-upstream = true;
          }
        ];
      };
    };

    # Generate local DNS records
    environment.etc."unbound/local-dns.conf".text =
      let
        # Base service records (always present)
        baseServices = [
          "search.lan. IN A ${clusterCfg.hosts.nexus.ip}"
          "ai.lan. IN A ${clusterCfg.hosts.nexus.ip}"
          "openwebui.lan. IN A ${clusterCfg.hosts.nexus.ip}"
          "haven.lan. IN A ${clusterCfg.hosts.nexus.ip}"
          "hermes.lan. IN A ${clusterCfg.hosts.nexus.ip}"
          "api.hermes.lan. IN A ${clusterCfg.hosts.nexus.ip}"
          "n8n.lan. IN A ${clusterCfg.hosts.nexus.ip}"
          "searxng.lan. IN A ${clusterCfg.hosts.nexus.ip}"
          "activepieces.lan. IN A ${clusterCfg.hosts.nexus.ip}"
        ];

        # Optional forge services
        forgeServices = lib.optionals (clusterCfg.hosts ? forge) [
          "mining.lan. IN A ${clusterCfg.hosts.forge.ip}"
        ];

        # Optional sentry services
        sentryServices = lib.optionals (clusterCfg.hosts ? sentry) [
          "monitoring.lan. IN A ${clusterCfg.hosts.sentry.ip}"
          "grafana.lan. IN A ${clusterCfg.hosts.sentry.ip}"
          "prometheus.lan. IN A ${clusterCfg.hosts.sentry.ip}"
        ];

        # All service records combined
        allServices = baseServices ++ forgeServices ++ sentryServices;

        # Host records
        hostRecords = lib.mapAttrsToList (name: host: "${name}.lan. IN A ${host.ip}")
          clusterCfg.hosts;
      in
      # Host records section
      (lib.optionalString dnsCfg.enableLanRecords (
        lib.concatMapStrings (record: "local-data: \"${record}\"\n") hostRecords
      )) +
      # Service records section
      (lib.optionalString dnsCfg.enableServiceRecords (
        lib.concatMapStrings (record: "local-data: \"${record}\"\n") allServices
      )) +
      # Tailscale mobile device
      "local-data: \"seeker.lan. IN A 100.84.24.43\"\n";

    # Static resolv.conf (prevent DHCP overrides)
    environment.etc."resolv.conf".text = ''
      # Generated by NixOS cluster-dns module - DO NOT MODIFY
      # Single source of truth: /etc/nixos/modules/network/cluster-dns.nix
      ${lib.concatStringsSep "\n" (map (d: "search ${d}") dnsCfg.searchDomains)}
      nameserver 127.0.0.1
      nameserver ::1
      options edns0 trust-ad
    '';

    # NetworkManager: don't manage DNS, we use unbound
    networking.networkmanager.dns = mkDefault "none";

    # Firewall: allow DNS traffic
    networking.firewall = {
      allowedUDPPorts = lib.mkOptionDefault [ 53 ];
      allowedTCPPorts = lib.mkOptionDefault [ 53 ];
      extraInputRules = lib.mkAfter ''
        ip saddr { 10.1.1.0/24, 10.244.0.0/16 } udp dport 53 accept
        ip saddr { 10.1.1.0/24, 10.244.0.0/16 } tcp dport 53 accept
      '';
    };

    # Populate /etc/hosts for compatibility
    networking.extraHosts = lib.mkBefore (
      lib.pipe clusterCfg.hosts [
        (lib.mapAttrsToList (name: host: "${host.ip} ${name}.lan ${name}"))
        (lib.concatStringsSep "\n")
      ]
    );
  };
}
