{ config, lib, pkgs, ... }:
let
  inherit (lib) mkIf mkBefore mkDefault;
  clusterCfg = config.clusterNetworking;
  # Cluster host IPs (hardcoded for reliability)
  hosts = {
    zephyr = "10.1.1.110";
    nexus = "10.1.1.120";
    forge = "10.1.1.130";
    sentry = "10.1.1.140";
    # K8s service ClusterIPs
    aiGateway = "10.15.67.242";
  };
  # Get DNS config - use or {} for safety in case the option doesn't exist
  dnsCfg = {
    enable = clusterCfg.unbound.enable or false;
    listenAddress = clusterCfg.unbound.listenAddress or null;
    upstreamServers = [
      "1.1.1.1@853"
      "1.0.0.1@853"
      "8.8.8.8@853"
      "8.8.4.4@853"
    ];
    searchDomains = config.networking.search or [];
    enableLanRecords = true;
    enableServiceRecords = true;
  };
in
{
  config = mkIf dnsCfg.enable {
    # Disable systemd-resolved (conflicts with unbound)
    services.resolved.enable = mkDefault false;

    # Configure unbound
    services.unbound = {
      enable = true;

      settings = {
        server = {
          # Listen on localhost and cluster IP
          interface = [
            (if dnsCfg.listenAddress != null && dnsCfg.listenAddress != "127.0.0.1"
              then dnsCfg.listenAddress
              else clusterCfg.ipAddress)
          ];

          # Allow queries from cluster network
          access-control = [
            "127.0.0.0/8 allow"
            "10.1.1.0/24 allow"
            "10.244.0.0/16 allow"
            "::1 allow"
            "fd00::/8 allow"
          ];

          # Performance tuning
          num-threads = 4;
          msg-cache-size = "128m";
          rrset-cache-size = "128m";

          # Privacy and security
          hide-identity = true;
          hide-version = true;
          tls-cert-bundle = "/etc/ssl/certs/ca-bundle.crt";

          # Include local DNS records
          include = [ "/etc/unbound/local-dns.conf" ];

          # Don't query localhost (prevent loops)
          do-not-query-localhost = true;
        };

        # Forward zones
        forward-zone = [
          # Tailscale DNS
          {
            name = "ts.net.";
            forward-addr = [
              "100.100.100.100"
              "fd7a:115c:a1e0::53"
            ];
          }
          # Everything else: use upstream DoT
          {
            name = ".";
            forward-addr = dnsCfg.upstreamServers;
            forward-tls-upstream = true;
          }
        ];
      };
    };

    # Generate local DNS records
    environment.etc."unbound/local-dns.conf".text =
      let
        # Base service records (always present)
        # K8s services via ClusterIP (accessible from cluster hosts)
        clusterServices = [
          "ai-inference.lan. IN A ${hosts.aiGateway}"
        ];
        # Services via Caddy Ingress (accessed via NodePort on Nexus)
        ingressServices = [
          "search.lan. IN A ${hosts.nexus}"
          "brain.lan. IN A ${hosts.nexus}"
          "openwebui.lan. IN A ${hosts.nexus}"
        ];
        # Services direct to host
        hostServices = [
          "ai.lan. IN A ${hosts.nexus}"
          "haven.lan. IN A ${hosts.nexus}"
          "hermes.lan. IN A ${hosts.nexus}"
          "api.hermes.lan. IN A ${hosts.nexus}"
          "n8n.lan. IN A ${hosts.nexus}"
          "searxng.lan. IN A ${hosts.nexus}"
          "activepieces.lan. IN A ${hosts.nexus}"
        ];

        # Optional forge services
        forgeServices = [
          "mining.lan. IN A ${hosts.forge}"
        ];

        # Optional sentry services
        sentryServices = [
          "monitoring.lan. IN A ${hosts.sentry}"
          "grafana.lan. IN A ${hosts.sentry}"
          "prometheus.lan. IN A ${hosts.sentry}"
        ];

        # All service records combined
        allServices = clusterServices ++ ingressServices ++ hostServices ++ forgeServices ++ sentryServices;

        # Host records
        hostRecords = lib.mapAttrsToList (name: ip: "${name}.lan. IN A ${ip}")
          hosts;
      in
      # Host records section
      (lib.optionalString dnsCfg.enableLanRecords (
        lib.concatMapStrings (record: "local-data: \"${record}\"\n") hostRecords
      )) +
      # Service records section
      (lib.optionalString dnsCfg.enableServiceRecords (
        lib.concatMapStrings (record: "local-data: \"${record}\"\n") allServices
      )) +
      # Tailscale mobile device
      "local-data: \"seeker.lan. IN A 100.84.24.43\"\n";

    # Static resolv.conf (prevent DHCP overrides)
    environment.etc."resolv.conf".text = ''
      # Generated by NixOS cluster-dns module - DO NOT MODIFY
      # Single source of truth: /etc/nixos/modules/network/cluster-dns.nix
      ${lib.concatStringsSep "\n" (map (d: "search ${d}") dnsCfg.searchDomains)}
      nameserver 127.0.0.1
      nameserver ::1
      options edns0 trust-ad
    '';

    # NetworkManager: don't manage DNS, we use unbound
    networking.networkmanager.dns = mkDefault "none";

    # Firewall: allow DNS traffic
    networking.firewall = {
      allowedUDPPorts = lib.mkOptionDefault [ 53 ];
      allowedTCPPorts = lib.mkOptionDefault [ 53 ];
      extraInputRules = lib.mkAfter ''
        ip saddr { 10.1.1.0/24, 10.244.0.0/16 } udp dport 53 accept
        ip saddr { 10.1.1.0/24, 10.244.0.0/16 } tcp dport 53 accept
      '';
    };

    # Populate /etc/hosts for compatibility
    networking.extraHosts = lib.mkBefore (
      lib.pipe hosts [
        (lib.mapAttrsToList (name: ip: "${ip} ${name}.lan ${name}"))
        (lib.concatStringsSep "\n")
      ]
    );
  };
}
