#!/usr/bin/env bash
#
# Setup OpenCode Environment
# Ensures LM Studio API key is available in user environment for OpenCode

set -euo pipefail

# Configuration
API_KEY_FILE="/run/agenix/lm-studio-api-key"
USER_ENV_FILE="/home/j_kro/.bashrc.d/opencode-gateway.sh"
FISH_ENV_FILE="/home/j_kro/.config/fish/conf.d/opencode-gateway.fish"

echo "Setting up OpenCode environment..."

# Check if API key file exists
if [[ ! -f "$API_KEY_FILE" ]]; then
    echo "ERROR: API key file not found: $API_KEY_FILE"
    echo "Please ensure LM Studio API key is configured with agenix"
    exit 1
fi

# Create directory for bash environment snippets
mkdir -p "$(dirname "$USER_ENV_FILE")"

# Create bash environment file
cat > "$USER_ENV_FILE" <<'EOF'
# OpenCode Gateway Environment
# Auto-generated by setup-opencode-env.sh

# Export LM Studio API key for OpenCode
if [[ -f /run/agenix/lm-studio-api-key ]]; then
    export LM_STUDIO_API_KEY="$(cat /run/agenix/lm-studio-api-key)"
fi

# Add gateway health check to PATH
if [[ -d /etc/nixos/scripts ]]; then
    export PATH="/etc/nixos/scripts:$PATH"
fi
EOF

echo "✓ Created bash environment file: $USER_ENV_FILE"

# Create fish environment file
mkdir -p "$(dirname "$FISH_ENV_FILE")"

cat > "$FISH_ENV_FILE" <<'EOF'
# OpenCode Gateway Environment
# Auto-generated by setup-opencode-env.sh

# Export LM Studio API key for OpenCode
if test -f /run/agenix/lm-studio-api-key
    set -gx LM_STUDIO_API_KEY (cat /run/agenix/lm-studio-api-key)
end

# Add gateway health check to PATH
if test -d /etc/nixos/scripts
    set -gx PATH /etc/nixos/scripts $PATH
end
EOF

echo "✓ Created fish environment file: $FISH_ENV_FILE"

# Source the bash file immediately
if [[ -n "$BASH_VERSION" ]]; then
    # shellcheck source=/dev/null disable=SC1091
    source "$USER_ENV_FILE" 2>/dev/null || true
    echo "✓ Sourced environment for current bash session"
fi

echo
echo "Environment setup complete!"
echo
echo "The LM Studio API key will be automatically loaded:"
echo "  - For new bash sessions (via .bashrc.d/opencode-gateway.sh)"
echo "  - For new fish sessions (via conf.d/opencode-gateway.fish)"
echo
echo "To use in the current session, run:"
echo "  source $USER_ENV_FILE"
echo
echo "Verify the setup:"
echo "  echo \$LM_STUDIO_API_KEY | head -c 20"
echo
echo "Test the gateway:"
echo "  opencode-gateway-health check"
