{config, ...}: let
  c = config.lib.stylix.colors;
  toHex = hex: "#" + hex;
  bg = toHex c.base00;
  fg = toHex c.base05;
  accent = toHex c.base0D;
  color0 = toHex c.base00;
  color1 = toHex c.base08;
  color2 = toHex c.base0B;
  color3 = toHex c.base0A;
  color4 = toHex c.base0D;
  color5 = toHex c.base0E;
  color6 = toHex c.base0C;
  color7 = toHex c.base05;
  color8 = toHex c.base03;
in {
  xdg.configFile."btop/themes/stylix.theme".text = ''
    theme[main_bg]="${bg}"
    theme[main_fg]="${fg}"
    theme[title]="${fg}"
    theme[hi_fg]="${accent}"
    theme[selected_bg]="${color8}"
    theme[selected_fg]="${accent}"
    theme[inactive_fg]="${color8}"
    theme[graph_text]="${fg}"
    theme[meter_bg]="${color8}"
    theme[proc_misc]="${fg}"
    theme[cpu_box]="${color5}"
    theme[mem_box]="${color2}"
    theme[net_box]="${color1}"
    theme[proc_box]="${accent}"
    theme[div_line]="${color8}"
    theme[temp_start]="${color2}"
    theme[temp_mid]="${color3}"
    theme[temp_end]="${color1}"
    theme[cpu_start]="${color6}"
    theme[cpu_mid]="${color4}"
    theme[cpu_end]="${color5}"
    theme[free_start]="${color5}"
    theme[free_mid]="${color4}"
    theme[free_end]="${color6}"
    theme[cached_start]="${color4}"
    theme[cached_mid]="${color6}"
    theme[cached_end]="${color5}"
    theme[available_start]="${color3}"
    theme[available_mid]="${color1}"
    theme[available_end]="${color1}"
    theme[used_start]="${color2}"
    theme[used_mid]="${color6}"
    theme[used_end]="${color4}"
    theme[download_start]="${color3}"
    theme[download_mid]="${color1}"
    theme[download_end]="${color1}"
    theme[upload_start]="${color2}"
    theme[upload_mid]="${color6}"
    theme[upload_end]="${color4}"
    theme[process_start]="${color6}"
    theme[process_mid]="${color4}"
    theme[process_end]="${color5}"
  '';
}
