{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.copyq;
in
{
  options.programs.copyq = {
    enable = lib.mkEnableOption "CopyQ - Advanced clipboard manager";

    enableTab = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable the main clipboard tab";
    };

    maxItems = lib.mkOption {
      type = lib.types.int;
      default = 200;
      description = "Maximum number of clipboard items to store";
    };

    pluginImage = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable image plugin for storing images";
    };

    pluginText = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable text plugin";
    };

    pluginHtml = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable HTML plugin";
    };

    syncClipboard = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Sync clipboard changes to history";
    };

    startServer = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Start CopyQ server on login";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ pkgs.copyq ];

    xdg.configFile."copyq/copyq.ini" = lib.mkIf cfg.enable {
      text = ''
        # CopyQ Configuration
        # Generated by NixOS module

        [General]
        icon=true
        clipboard_syncing=${
          if cfg.syncClipboard then "true" else "false"
        }
        max_items=${toString cfg.maxItems}
        paste_selected=false
        confirm_paste=true
        paste_ascii_control_characters=true

        [History]
        show_in_tray=true
        enable_shortcuts=true
        tray_store_clipboard=true
        item_title_format=%s
        text_wrap=true

        [Plugins]
        ${if cfg.pluginImage then "Image=true" else "Image=false"}
        ${if cfg.pluginText then "Text=true" else "Text=false"}
        ${if cfg.pluginHtml then "Html=true" else "Html=false"}
        Data=true
        URI=true

        [Commands]
        1.command=copyq: tab "&Main"
        1.icon=go-down
        1.name=Next Item
        1.shortcut=j
        1.inmenu=true

        2.command=copyq: tab "&Main"
        2.icon=go-up
        2.name=Previous Item
        2.shortcut=k
        2.inmenu=true
      '';
    };

    home.activation.copyq-starter = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      $VERBOSE_ECHO "Configuring CopyQ clipboard manager"

      # Stop any existing CopyQ instance
      ${pkgs.copyq}/bin/copyq exit 2>/dev/null || true

      # Only start if enabled
      ${lib.optionalString cfg.startServer ''
        # Start CopyQ server in background
        nohup ${pkgs.copyq}/bin/copyq start &
        echo "CopyQ started"
      ''}
    '';
  };
}