{
	"data": "ENC[AES256_GCM,data:YM8uCtZ4CYnsLExZPWAjDJRC9K+87BeotzFNqucGwbZd1xwYF0fhb6zqlOBj0PMpG2oa8a24+UJgw9Mo2vq8AyaUkJIS8c0D+a6isUCM3TpmYM+zsU+faB7JcbO1/qsacULssnMSArfp22WEjNToCExVFpTF6NHuOs/8QxGHwALQv31svPepPoe5Q5VIkT03da/c9L2zX002fPNtiOOL3xEVcg8AwYiHvr2FH9iI2S9YtZ9iT898MaDwt/UnfJUzcvLMaf9yzFESgUSJNhYW6OMn1HtKqwq99hFzn7XnMh0uGWqLA8BZ/RxlSthd3jLFV8GZGf1Kikk9gBGJfk7bLQkj0Bl4I4fxH8Tu23SNVDtxMmsFy4TMmJzzoDEUjQkjIjNE5Y14J+QFKxrrkqj/JNfw1LtN7k7Km2ewdqW5YkfrrFlx5i3+KNbilQdZGJjeEjR7DVq/etqeIT0EKo+cA6nL3OktARZAVkaXzVfj7ZWXaGh48rTpnha62JmFkXQpky6nwfKZ7pTGkhKPdw5/,iv:ju3Q2NCx1FKrWuMx4LHFq0RazvTqshWqRGZLDFLz17c=,tag:9dFSpU3pn583IIKL9C5opw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTS9lTHRVL2NYYmZyTmdN\nd3JXNjB1bUZKSWJ4OHdvSEU3aGlwRmFOcEcwCkEzSTNkaUtPd2xSVEJ4Ym9Sa2g0\ncGVmV2Z4Vk5iMGVnaWp3MFFLRTdWL0kKLS0tIEQrUzh4N3NKbVpzMjVpWllOU0RP\nQzlyS0FMZGZkTzhvMnlRbHZvbjBWMnMKpdirVYbkUZbsrD2rPYiEToR/8bc/eyp/\n5/rJv5FojUmHbWhdSnaUGM53x6URbobQ/tUQ9hYSS362ukOtD5Leug==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:06Z",
		"mac": "ENC[AES256_GCM,data:jJXQ7oAIB3frixDRtNPHpli2HH6Uow/Bm0/cMGDs10akmI9cm3f52QCJzWjwI1Hx8LfojYp0aFDxFVq0wBjdXAVY2j92ScgoTnLxuEX1+iSEV2hOKumv8Yqsc9cMywb2Zba/OYydYmTp7eGBr4zirgbU2oKV+PJ5Ep+T/hhMdCE=,iv:qP531NcKqtJDKf0KSq7wJ1h4QWRfetStyRAr5u6rg5s=,tag:/EuR5vJ/hJtzgRHO6M+CkQ==,type:str]",
		"version": "3.13.1"
	}
}
