{
	"data": "ENC[AES256_GCM,data:Cac+WkhC8jHMfFsnuUV7Y5q2hKX0wQchD1g01Z4ozvUCzTXuMVLhOP5zYFog7qBZWaKZHhv/25GB7g1OATaKNWuEf+E3ww==,iv:ik3ic8cDG2QuMBIMxPhjEVpgDtFxfDWJxEYe26AyRlU=,tag:UINLOPYhlxatn8Isw5NU4Q==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRzVMZXM0NWZBU0JTMC94\ndDV0STlVZS9jbmxxZC81MFJ3ei9QSllwMTNVCjdmZ1BqWUJpeW56Q201WFZsSDlq\nU3IzdkNTbkxPdzRISDVnU0Rsdm5wTlkKLS0tIGQzdXBPMUNTVWRsUk5VWlcwTUVV\nRWgydDBZempoUGdETlE1eFIzVFE5RnMKygf2dTgLQ942ZxzrMuDZnss6I/blrS08\nGMMgNkxAXuKHerwfCTOQDsXaqznnhj4ukDcr8fzzdI3F2UaDv0b4Lg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1567g6raae4adh97lrfhalc9wwhmtsulh89k9pkx24m5ezfh8a4xqndrt6l"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UTNVU0FMQ3VTZTlIeU9o\nRWFjck5xL1VDWVpNVllMbUpSVTZrWDlvRTBBCkp6VUFIdHpHaURHeGI3OGx1NlJk\nL2pFVG8xdDQxWWlhSnlnK0kwTjJUSXcKLS0tIDVMbHNlekJjUDQzSnBaaUVZZWV1\neFBuOG5MSXdXNCs5RDdjcUxMM0xmM0kK5Vg85gYuwhVw8Vi6Ah8YZYwny3LoV1Lm\nhMXwikNDPTP8gcKkMVgJYdY1IL+Zwq1T7W4yHHhGJd6GlSeq0tqt7w==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age12k7ch5r9sczu42zc6eutxtl6leudn47uv5fvsjrlq5ms0f0hz9nshm3t7q"
			}
		],
		"lastmodified": "2026-08-18T12:22:18Z",
		"mac": "ENC[AES256_GCM,data:f91CU9PELMODUiU7dvp1UiX8ZPWj7GcBgknXTCYsb85V19lHDdfXSlUefgP78mD1437Ge/8VBYwPdxEtB2YbiKxDbiRBcsyP8XEBLWjZojn6QOASV1GU7DnZoHnKuctGhFeX4EfVo6ptGRS+e3OX5WZFG36om5dNYkgZ9mevhwQ=,iv:rVdjLOWDWSGO3DnAyJ6WZ3JyROdBXrYNjfrmt7XSSiA=,tag:6nuC1/ib33q+p8qkPGRuIw==,type:str]",
		"version": "3.13.3"
	}
}
