{
	"data": "ENC[AES256_GCM,data:ZZZQgPcKN9ZLf/Ee9lSH/VT7Vz8cOqjucC0d3jn7/rUnUPuiV4NAEoQYY495FkTLMz/cSO3FXl253jB9Quh5ZtqvXcf0ctZAf1oO6nBlkExyY8P/bpDKHP+X3L1FIBKiuRdjWYq5EJTxKovKi+/5vjaPXuwm7x1I1y2Jy7F6pwUI2Kth7XC9riCNDxplWnjpasEKsG+ySvy0LD8Fiv1sWrlLsNGVjkyoxCw0eB/6VF8oRWXBsMdvTislZknw2ri2cSpgyO/xgzrBYkQZrkQ5ZrkQqr9nTNSWgOrouvKPHEz+5++Npzuam6K8ebkWWLmb0nl2zTGiiCkYhquCaoESSJiAAf8VHy50VVs3MuOUxBuRvPC7/gtIEnou0hxV7ZPQfCXFduxHNw7cbPnmf4a6AZCmHy6VXkV9kXuC0tDZuJnTdBviT+Y6hTbCJpejJAJyDdI3wD653YuG4nKpSbi58pg0OW7s1SBREewsSidgd+fnUsnfFOBBKVRpJ0ox8DObIfY/zDGreqhmJp/xOu6K,iv:SOxM0Nz6IDm03QqFmcOoHOFfSOF00bLi4UeadVuuQkQ=,tag:eyjviqukhJtWjpah2A9RYg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoa0s1U1hMdXhmOUFOR0J4\nTm5XWUF3aW04V25lS2VvQ0VkUmwvQnE1dFdZClVUUVJUUXZYNUxSa2UzUWJsQkg2\nZkM3TzlOa1ExQjUxaXRkNVBEbWo3VGMKLS0tIHJuQ3ZFZDIzWDNwaEtGQklidEM5\nWjJXaUZOK3cvOXJnSVVaNWhCVVJMaG8KrkrQNixaNriJ49VaaErtdWJM6N+ltN0m\n7YvFIuc/G5Nq/xz0zACw5Hw2gTjv/b794XALzM5bCPXrG51j7myX+Q==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:23Z",
		"mac": "ENC[AES256_GCM,data:Km0IZ4xgK1W789ps1IY854aIcN67b7HKpZDpUjib2psnVJHg7Wo8pXX/X6UAQuFoAHuNgBRP7ykuF/crcCIKMwWQYAEHh9WC4Sf1zG2LhWZRG6dGwgS8FW+1hKZD8apsAUAQwXnnlKlJdcZCxxHBRGO2MPJ0YdD0SOZCRoRaNbI=,iv:OI6Zp7I/SgRtQlWi+IDoiyLOlGDmoZgT3bBxjtyGaPs=,tag:IdXCII3pp/5v4FkglYVasg==,type:str]",
		"version": "3.13.1"
	}
}
