{
	"data": "ENC[AES256_GCM,data:X8tCxDELa6D2t28CKDL67EaW5vh+NR4bmDwpqx/RBGOX+x9YWNWH8k1NX2nKsKZvMdz05H+iLGN9gq4K+E/F1EDCYMuFrbZ430Y0bYlgCeBRoH3nN048OMzzfLIUyn4ep26iZcdULEfSRpeZJb1KdG5SGYc6pdFdMstKxZRuaT3pOJhxma2tl2NbdroXlwBRQHMYUZioJMjxpdDesQPUBup8j5D1oRAjREpqtJznkMm9ssn0H3epUw0zr8UCUUDKyYRVA+GN2XFQzVAD95AlNHN+RevIVKGuo4D4T+MTVN4uQlv85rvQ5/KjfWC16z3lcnxwuSKHTOL+2B7xfw+Zw8NNXd4QcokE3SMG4rq9yCpHhsGU1YxqN8rP9fewDaU3hA/lDeclKqlBPVqusVE9EK4A6H0xdXs55/MVw2EjCypvgMlfP3tj8aCvgYb8fT+eDP8h2oJOZbCuhCIFchWaQ7DEu06+Un6I4bqI1U1VylwF9ppGwbZ8PjyQaMy9mISly5eCO78H5VnENAZGQErp,iv:yZMkkv+2ly6fABzP0WujHyA4BUxLMp9Zoz9r0WJTIq0=,tag:jQzZ0ygpTgePzcc8yvVMAQ==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbFNRNytsazdkSWNPOUJm\nbjBzTHVZbGxPd1BiOVd1ck5PWEhEWkwrSzNnCmxNZkZiY202SHRoQjM0N1A5UnU5\nYkFza1pLMmRsMVBGMUp1RnhIV093ME0KLS0tIGNkcTduV3pJek1XN1JmRk82SWwx\nWWo5THlxdkRYWFlvYW5HbUlWN0tQQW8KJtBn8PoeHzbj+ye56vWAbpXUvFG/nbXL\nW2i66vfBPdSeR1fUzaflVWu3eINr9xXNq7p7lAe9SCLlmw2O/GtszQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:20Z",
		"mac": "ENC[AES256_GCM,data:V+lb0t0ooAwkCKjY1TMlFESpG7MkkCxe1HDJv0Wz8ovhl3wv3WKHDZY20GeoE/9PcEnnYVnv9Zt3gzZ+7CkeNoZnzJUO6bB8e8nMrwhKV1BBLRhZNatu+kEX00DDNb1/xhgiZyOl0189Hm0gkdKEskuBZp8xm4EusPI/5dgFsGY=,iv:e/u3oV4NA6BBUavuiQfhZDjSXNF6AkUKk7K3nE5RhUA=,tag:gKpmefwEcWUHV7KiWkIk2g==,type:str]",
		"version": "3.13.1"
	}
}
