{
	"data": "ENC[AES256_GCM,data:g9+/2TPcrYuFovcr8jm5j/OH1d28R97gcb0r12YDnplYf8bHTwGmLGDhYAR3mOZON7RCEmr4eAXli2uXNDmh8K+yCMO0Eb16aZA6TfiDb0PwALwYniOnyJwuynuRr6GBoRCErTfIL2rrdnnZS7bpbulAJ/GMvgcr9AuZHNicHQrMMYzU/QQXZueF+9HfWShYuUyCRpiNWFgVohnt1no0QMnWMsUxKUeYcr9C7poJVZiob14TL6DSJPNuZBwR4fUOUW0kHeyWz+3OZzWJBse3r78Ivd3aGB0Pa7z7m6XTKe7ZPi6Iac8b7RswVfrJ3KIpkobj+kptoKeudYRiQH9Fe53CmRjDs1TSp2IXt8W8i8JIZXmRJcuuEc0URDu6AUb4xmNYt1k+yc8QrvCzi2wLxwuuzwb1z37yo0DrMG+ZygrMm4uNMU17JtHwlhI46rDFpFLJhjCauvNJc/ySl4SZMCI6hc2Ln4568N8zaU3diDazHoB7QBrL9s3sGTgxEVdk54XwHLIKF1Hr1rxkC68w,iv:GqeDCXP7csvqg2n164CTgEKFr/692pOD47k3mGPB8Fo=,tag:ullHePK1iNFfb2iQGgG8Fw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aVBQdW03TmhKZG1nUkEr\nU3JneGZONzExUUpqNHQ0OXpHcVJGd1pKOW40CkpDNExJZ0ZFSWlVaHdBSGQ5cmRY\nU1hKbVk2RWwza0NtSHllWVNPa2RSU1EKLS0tIFlQakhaNyt1V212ZjRORFJkZ1A5\nMkVEd2E2dnJRNTBSRW1iVGNlRTVGamcKEcr2tB6yS0+trWqw3aR6lXHa21AmbUme\nVw0oQwyLMkdkyLk9ae3hrQNDe4/u0G300AbnylPm1nIfW4mJVJrtPA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:21Z",
		"mac": "ENC[AES256_GCM,data:vG0c4ekbAzg2TgZyN1IuF15P5g+qOnZZY/1weIyZzkkUKhuihgIG5H+ouhklXGVFyo0mFeE9vGQCkdhcSFb3LY46fpMwz9iNtfOtWxOtAzvp4kmIxidFhNxu8VOnQkrVkAZqttfSsf2IySOBzWhF7pVjqWXIHPJ5QpRVrb1CmpI=,iv:2DfNtZuDVOK871qxmLUWMXueiDr1y3n9XcbAORHcvQw=,tag:OZOs6U6gbNOLSSe4Bz7WWA==,type:str]",
		"version": "3.13.1"
	}
}
