data: ENC[AES256_GCM,data:5/9KKq2vMc4cDX6migojS69PexCDDEAxDJHw9oDzIiI=,iv:Yg/fL05KcBktsy+fDq63m2fPu1tqfjSai+MvEtt0ixo=,tag:A4pyBrXjoXT/zZQV2z/YFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT0xrK0sySkd6ek9UTnYv
            ZnU3L2MrdjNmRExhL0kxaFBVWHFOVTRtd0E4CjBBMEo1RTJxR2wzUG9kK04zVm9L
            amRncEtqTXJORlg4VHdTWmtDTjVCVEUKLS0tIEIxaHo0MHpiNExyL0Z6eGRVVStU
            dlJoU2tFRjM2QzQycW53ekhPNnd5UkkKOlogXvTakwoBc6sEz22dXLqbcqdY85Dn
            Bw6lXsJFidQBPSEMkV1Q3ZDpEPnWEqQaJfMu/PU5uDhaY0X/gb2rvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBNktwczV3
            Z2tETkxKdExxMFp0aTZIK0hXSGdQUjVZdE8zMks1cm1pSFpiNgpnL25mWkZMZ2dm
            UkE2ZkNFMmt1Tm5LQWRudERmRGpiUms1UDJ4WklFcldVCi0tLSAyUGkyVTU4OWxR
            RnlVOWMvaThkd2g0R2RucUozaTVrTWxPZlBYeTloRklrClsN2jKcF2fmaJVEWixI
            jvCUj7+eeu7ODPokLdeDt4OS4WBwn1YHweZaFafR8l77HoyrgW7DFWQDM9e0oTj5
            gc8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBMUNLTGR2
            dllhOFRPWnc4UXd0K0I3QmV1VExnZXN0a0w2ZDlOUDFvLzQwWgpEQWE5dG4yOTlp
            dHBOcTRqN3o4N3o0bUh6QW5qMU11elI0UHN2UmlwaHFrCi0tLSBqRUVtcXBrZ09S
            aEVJZ1RTcUhncU5OTXdGZ3ZlMkFJdXZLUlg2MDBwVWJZCjUzHBe844SShAYJvBNh
            1t12e2oU+1mYatLINZfPP3JZNZFcnaEfroQpZ8m2rqb3h0/H9QPf4ct2zaClFFXr
            YYA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycEc2M1J6aUpyQUFpSXNW
            VTQvMGlZc2szSjRMMXpaRzExTU9rekU3ZW1rCk4za1NWcnNkVlhIcVFaQytUbkF2
            WlhtbVlIZ3B2Tk9jQjZhWkRxMkF5NW8KLS0tIEptNmhDQ1hvWlFSck9hUkwxM3pI
            OFdvQXIvbWcyZldlWWFTRk9jRkhFOUkKSClyUVkUvPGA2MGxKtvm8p369uYANhe1
            Q5L3XX7tTlR/kwN9fpKhefBnGWmmg7aLs3Mqrkbr4likSCN6BOMXRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ehx7aedejaf3tqje43h4nj33c3s4nctet6mpys9pyegz4wexa3jqhgg0dz
    lastmodified: "2026-07-14T12:33:49Z"
    mac: ENC[AES256_GCM,data:3m2Nr1woiSIs5jyL56Ai7l1pp0Q19rod6OWzLk9Qjajp1XgFUt5NyMFbk+ZFo2UVsNc7oq89Y1qs+uokqJykzz0SXypIZblVuf2FaoYtJFbY6SIWfc4QRe01YACO22f/0zq31VMAels7is8BFcGJa0GKcHLa9tF4bsDIYS2Gfbg=,iv:wtM8Mh6qNIob+E9JHjMBZ2vU+OGUkBouS6BM2hgx5GA=,tag:1l59rZSo+nWqZdLIoRTruw==,type:str]
    version: 3.13.1
