k3s_encryption_key: ENC[AES256_GCM,data:RfpC5L2YyJFTDj96G+NzeLayFB+ium9jr16tG78TZHD2X3sZKFU=,iv:YiBe9RE6rj1vSdvhKdsEZELYh3NbjH/mGwdCA92yqiM=,tag:ymg++7szza8fnJi8bQf7lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORWo1YzU1bGpjMUtIdkZj
            OXhHaitKdzdhMzY3eUliZ2U3dVNwWW5iUW4wCm1FdW1NTEM2K05FOENDVitSNDg0
            OGhhRllYRWVLYytwY3prMllYS245eGMKLS0tIC9QODA3UGpleTRJOWpobmFVQWlp
            Sm5iWENaVW81VUJBVnI5S01XTUJBdW8KRM/Q2q0jBjXYhY/ygbdjx648bk5646RH
            yGp8ZOOT1OaOPpPjl7iHWgdpKricitxY3Bhfkp8x7M0h+lDE4z3ZIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBZ2hhU1I2
            U1cwS292Q2tXQi83NnVOYnFhYkllTGdiOHRmY1NocTVVL3c5TgpFZ0ZGdCtCaEFr
            cXZ1Y2hkQ3pzcHZnUjJ1RHZDRi9hRm90dzNFeEsvbkQ0Ci0tLSAzMUZDdGhyNk9Z
            bGFHMEFFUFIvSldIaS9ZOEZvT293M0JsVVFwYXNrOXFZCsBeRh8ovOe4mLsd4Yms
            h50rgdYGgLyZGQzi5jY/Ron7CdMoeLRoj0G85VJWUDim4LuRks1CImYrwebEHGJr
            k+4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBL2VUOFF0
            OG16ZEtnSVoxNmgvVGtzRlloaUY1OHI0M3hHTkN5T3hUSVBJaworLzlTMmUrU29m
            WDkxQ2d3cHJsSzVMZW5WeEl5WXR4UkZ0UXprSzViZVFNCi0tLSBBM2FkUlBLNjdS
            WGlZb2wxZEh5dmdqVlZWeHk2K09SdXVhSWgralNDNVpZChDd1T3Lj+3Pv9KHYbc4
            JIofDXztyuIxaVTc0VTDCA7eSjJQooWCOkonHeis1ZMlMQ97h/vFDiZn5Zm0j7bf
            8BQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-07-25T18:48:29Z"
    mac: ENC[AES256_GCM,data:1TIEfoOHsgOYj9Np+5qOB44dXKi8oucx4XR2nO8gAvEDFiUa6MKJciPOzBW0fM4v5hGKCte22KoYsH8DDR8zzV+tx0RDJAsLLU4zB4F9E3KG9Xm18Rl8cO+1bnKzecmV9haYWLfXnVkBT7uFD3gVg8PT29TnaFqtjVZHk4rs1Ac=,iv:O3D3FyC19HDEZvjW5D3CHKDYF4V++btZ2JFN2/W8rU8=,tag:/tRN8kdi9Z8TEfxjCeJx7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
