k3s_encryption_key: ENC[AES256_GCM,data:HLs4Ht5cn8zT0Hk0NGXQ1UC2hiVt+w5uWq2EgPIAFTNWaiw1479pwfAGQ8s=,iv:fsS+V74IciQ4WbTGvS9GgrnzwwB3ozX4gsZlKBb3Igg=,tag:hiwM0Fp4iFsrAelXigvxEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aW5tbUhheStqL1MzTlg1
            M0JndDZieHAwZEhjN0w1QmFKSzdVUnlQV3l3ClhCV1QwT0JDdW5JV29zOWt6bWE2
            TmpXK0JzdCtlWU1MaFFhdzNkbFRoSnMKLS0tIE9UcXl5eEhhODl3WjgveXFrZzMx
            K1FFeE1hWFlPM2JxblNKTENOZi8yWTQKRr2Mvy5twc89fRmZf+XmrcMu1AWj0Nj+
            jXWeJbllI7xn5i9l/uAHo22/BA32MXmvuWwvp8/v3DONM11H8R7Pxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1567g6raae4adh97lrfhalc9wwhmtsulh89k9pkx24m5ezfh8a4xqndrt6l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c1AxUFNpdW5LREpyc1hV
            cy9Oci9RNHRqMWhzTzUzMXZTaENzeHFaY2lJCnF5TWJjei9UNVRlbktnc09WQ1ZD
            RXJKOGtsd3FSOTg0OWNMamdZdEY4d2MKLS0tIDlEbXM5R2QvMVpQdmVkTEJhUzV4
            NHVlSkJwMzE3Rkc2MFZmSm5wUUxJMUUKhtKoD+iKdVKCWrVWQUNHLQOAyk3T5Cew
            Tgteox33IpPgxv+V2W6qwy+TDQGjv8hIpIkvOVuT4X5fyAcjuQSLZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12k7ch5r9sczu42zc6eutxtl6leudn47uv5fvsjrlq5ms0f0hz9nshm3t7q
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBeml0Tnhr
            OVRtSi9CcllnQWdHSGxTTmRpM2pDZmxGdkYvem96YnhCZGw3WQpiU1ZmSzFvcE13
            M0MrZFJvWnhKdWlOVUlsdGtYL3Bmdkg4dzJ2bzJJL0Y0Ci0tLSB5UkFQQ2RIS3Ba
            QVlFL3FJdThmOVd0bk9YTEJZMHFpOXZkZkJEcGhUb2hvChitXsKB4yVzGkhNR6dt
            jyyMPtluPVdGtZVED3991eGn105IDIIY7VGh3XtmbOU9X592GeH/dChAkfurqrFb
            /OQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBMG9kK2hU
            d3NZRXcwSU9YT3R0N25pMHBrWkRLRkQ5ZFl6QzJZZDhlQkFTRQoyakt3bkFYSndq
            VGoyNk9xbHBKV3ZmVVFKQ1NaOEgvZFBlMGxRU21rMXFZCi0tLSA4T0huaUpHMHJO
            Z294MFk3OGQ1MDdvNVhQblJYWVIrVFhDNWZ2NWtMSnp3ChLW6PVYuaDIt8cRq2qn
            vbQf0KQ4ksx/Nqm48k41uUYYq1P9GPEmo6xZl6ZYVSnnIxTr1GpYRFN1BuamD4Gf
            NUw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-08-08T02:34:03Z"
    mac: ENC[AES256_GCM,data:cduu0MmuhWsG9M/oMgHqt4AOcAqrNp4wT0Ug/THfOaOeXG/LitwrqKoQoOuiZP+sviDto9j5IOijkY9TksrsZIQ9NLUAYyG9WOuH2VRdSPjuNondtr32LH2TdpwLkuhRafwp1W16e4ljjQAvhSHIf7LDlVnr1dsKk0Ub+rGS7pU=,iv:wtt74mXUDHUSfiyH+t+ggvOFztG0PeF/peJa7diwBvg=,tag:zpEZT6Wr7M+5Q2amiUldDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
