data: ENC[AES256_GCM,data:PAlX62X1AFylAoyYdtJvqftlRne7QXov,iv:13BrWSJeEmFzO8N400u48088uo44MaY0c9y+Pmow9T8=,tag:O+SabJBhoM4TqX7sm4z1Lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OUkxNkh6SW9hS2RRSXdJ
            Vms3L1pJbmhiRG5idUN3OFlvUm5GNlloVmpvCmxYN2dDVG5DdE13L3RyOVdxZnVB
            bFl1TUcyRFRvbyswc2RQTXhGeW9nSE0KLS0tIFQyQXMwV0U2bU0xTVZkak9JZW1j
            ZUV1OTZEWEg4RzNlL2d5TXBSN3B0Z28K5kg+qJ/BCEb7fnEBsroZEUizx8Ex0IxS
            BM71k+YuW3kr/d7zSkQ/sFqnUvnP3r9YHh1/ljZKJqZ3pBTRGK2XWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1567g6raae4adh97lrfhalc9wwhmtsulh89k9pkx24m5ezfh8a4xqndrt6l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmempnamhMOG5uQmdGQWhR
            NXdnU3g4WHR4aGlRT1Nic0kvMUc2TXhsSng4CkxJV3pZTTl6Z2o5ZTlWb2s3My9Y
            UFJRU1FkUUlaSm55VEpvYW9yZzMyVWsKLS0tIFJsK2JrZzhmblRKK0xTWHVjNnV3
            OGE4a096YTN2c0h4RTNUVklXR1VWQW8KowPWcA/49GPkvQn0a1aMih7Vu+umn4z7
            eQpY2d8DkMZhP+ondwMAc3KL7pDC2OOuGu61o/Ly0tQyveKvOda7Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12k7ch5r9sczu42zc6eutxtl6leudn47uv5fvsjrlq5ms0f0hz9nshm3t7q
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBZzIwMVRV
            RDNYQ21Zb2hTRHgvZEJUZXZvZGhXb2Q3OVJnaUZjTDExMVo2WgorWUxSRzA2WGhp
            Y1VZRW02Uk9yUjEzNS9qbjZmZG9wRDlYRXJ3Yk4yYzRvCi0tLSBDSFU1T0tkTmph
            bWVwVjd0T0h3ZFRoODVEVGFrRy9vNUpoejhGb09mK2RjCrAgTS2TXzSdHX9p66WG
            i5vRCqcRKhCnLE4yVR0tv/G836GOHKlIhFGNinRMgSkjPWkVR6HBbghThAEF8Vlh
            Qqg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBOTJVdWF5
            TlgzTzVFdmRkTXRjRmEyd3dEOWZjS3lIYXZzMElRbWNiazRQbwpHMDdRZFZwZXFl
            MnF5eWxqaERMcUdjV0dYbjQySnY4ZkRGMEV2NGwzT0ZJCi0tLSBZNDJ0emZIcG1i
            MkIxSDBPZ0FtVnF3d0Y5Rk1CZjN6SzVPTHNDTkRaWXowCvpjf3ReqCnjn9sHXJ1R
            6IZJpYHfeGaNzSpzpFIKMbS+IuVZuXYae7FUgfGcOwufhi6vBl5OiqlwjWpmnDbQ
            PL8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2
    lastmodified: "2026-08-01T22:48:22Z"
    mac: ENC[AES256_GCM,data:7WmmWgquUuvORJ3rc0lOrc3KbMXLvU5GoWC9VgV1hhgXwZIGnpg88NG9P21LwUWx43jvH5H8Xn+j/bnawZS+gqh/SyxinPrmBRj/uWIBCXN+xv09zs2RN/17CgLQ6j9Eab/zPF/em/WsRv+nFkJvDh0TAp6BWzxCTbEjbPjASOI=,iv:p/IwljpX/hGsGYX6Xjq6mSja4VKw+14k5cDzKYsZyGA=,tag:IEz3JWN3voGWbZ8aKLOSew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
