{
	"data": "ENC[AES256_GCM,data:gVNYnD0Ue2wMmkmTwN9ldFPUeAWQWs6OleQrroqnPzc3SJUwyFz9dsWGVhoA2P8xr0zb1PbAMc2MrBU4UNNI0qG7lKs5X3TMugTBpRshQSxpbLR2O+Zv96xwBp7xYJW85xYW2CVR+fz9x6m0SDMwCFiR2ELmbNqlho7nDmez9sYHSlzIhrod9HuiomIsB3PSY+ZH6iJvSnNYbsUeFMmBJ7m9fD7owAmd/cOb5AhlRke/3JMsSg9zKVS7bY1CqySsoY6eY5b9RhheqDyGNYCI5O07F4GnP7i5onLka7o0EKysikkbfVju8fIJP6n/SiALyvLOvDL31ZxPJOJ3RQwquJpqg5NcRnrEcPH/ofmmJRwBh+9Ebro0M7Hc0FiCQGxW44da+3jCwor5Bjmjudb4xx++nN5QeI2zyfbOtyva9a5T4JNE4oXSet65Cfy/wFhcchwKpzQ3daARN56NtJEtnsGgbtzAUBEX83ajY6xTg80DQngxZ0z+Eg4eVqEKzoY3518K9aqNmShkeO2aVJTy7E8tZmEKLkmnZ5tyeVykQyn6TLoQnEGRffhEkeq2vWRehmJKzQR8x4TGi5K4I1sHn18p+KdTgEg=,iv:4LawnFC0SlPo9HKPmiQGNCZmYh5CE7H8fM7atTK3ni8=,tag:poiiPlbT0G6ZP0mJ+d1E0Q==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUDJaVERqVEhzTU51YUJK\nRXZteWZhU3B3cDRWM1ROcnhGUXAwU3RMaGhNCmdOb3J5QW1jMjUxa09udDhoYUNL\nVFlQSGwwazdEZHdZUlE3bEJBVlNNVmcKLS0tIGRFaGZHaUVrOGt1c1pGYXNWdXFy\nT0hQSjlLK29BNVhKMGwvY1hXWXUzTEEKpxMtlJ2CESTfqVqQTZ/oja8zmjXmN/Dz\nCMsLBHpvkB9R+uHbeDp9JusNYmVGO8Re8tvy/73dHw1ULhW5BGFvdg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSVcvNGJzei9rOTJZME1D\neVRTTWJzYzU3Y1VzNmtGM3o3VEVLVW1SY2wwCk1vTjRtc285MWVSTlBSVHZ3TWQ2\nSWZucWRGUC91MTZWTi9NM2tBUi90QXcKLS0tIGhJTFY0bGpoV0FqYXVLWXJOUWts\nZURweTFnNkhVaGwweFJiL2hVN2I1b0kK78k164fKef4NGa6OmhHPIgubnG66mzq8\nRZvXnPUEjEWA+PuUx73fv/CeeO2f/OL2zl7nxJdkqC9yR9mCAh6dZg==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBaXJ3QzJZ\nUFNvOUk4Sm05algrL0R6Z0xDdGFpZWZwUWFRR2RLSkhHb2VDRApWcUsramdjT2ZW\nSlJ6emEveGNwRzJ2TzR0UHE5WDExbHVLZDFhdWNDa1JJCi0tLSBTNmt5QXE3Qy9E\nWndtTkJpdk45L2U4REFmcFF3ZVBheGErNEhnTEQ4YW9BChIO5FbNdf/6+yQ4ozcF\nMRSJoPW84teDnFeDIJBgbaQBOWd88C2TT3jlGHecz/3CG2TzGJUiBFUYVpp3yrSE\n4vI=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBN1RpUThl\nMFQxUWdzWkc2YTBDU3U0WndCVzllL0xiN293cjRPa0pCSzVlZgp2Qmo0S2pkekZG\nSFZtM3dQTHcrN2RNS2wwTGdXZHB1Q3EzVHdlSVIwUDBZCi0tLSBoOWVKdTZuVnha\nU25kTlZJYjVaQTBqUlo5TnNhQWNNTkhwZlRHSVBqS000Cuxa0D0j3b/9PEJ89NEp\nx/44CGyCpDbNYekTQWWSRjO+hvWopz/9o9xsYiwta+1wWUHvCEbTZFYK1m9dwhQz\nGdI=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2"
			}
		],
		"lastmodified": "2026-07-25T22:31:29Z",
		"mac": "ENC[AES256_GCM,data:2swRF0x6Q5vR6Pu+0g2gUuV3QZCwDHkIFQ1C7DQMqIf7HELqqFW0Poz8WrDSMbbQqvFOdau0tzs4LmnfxbghbA/GVbB5vm594j5tYVaYiz78wpywP6gLU425waf1HVvjuT1s59TwTbEfsKwhuRFbM4FQgIEHMQm6JCmhVoGPD2c=,iv:weOsGmXFmVoDSSlRC7Tel6oA0/+R6JBJ+KqcolC+sfk=,tag:mJclBeLSWPqGACgDOn8Axw==,type:str]",
		"version": "3.13.1"
	}
}
