{
	"data": "ENC[AES256_GCM,data:2VmgJ1HspS3iPNlIugVLn8uWOjzQR/MBDcv9w3tch8ObfqqHuPlRuRpHKC73BxAvz2DNikCzj+JOgOeB1/Eg62JoMNfvvvTD3k3Ucn3l0wroTcVpto0FM1G1kBNTPDUISXSPznlLAi4MxKDsPgosm8BCow027YdlAGhq83A0mWepckRirHg79KtQe0UnTvjpXxII7G+IdxX5q/1y2tPsdqLx2nmdeeCjzur7eUa2kcdH1veoodlsD/xIvPCiEEKMFet3eufFgG8dl22lihAkpPLxok3z6mZT1zdARKsJTZdskkdQsrUPckzrXwvAtIIsNwnITBSISGTkhnZaBt4ltUy1r38oJcBfhh+82602LawKmQOqlqgkg64KHEvCHKTUs0sr+4tyxxh9EjQs+lcWFU2ztADEqHySp1z9vZzAwG1a4t0bbily2HvnEPpSdsY6MmWaKJhT32vZQmoWYQ/aVby9OO7GHOCCyWjp4p10u9VSuKxQDUIxvWpe5nXYEx26ZfU5Wz6dHD6WRPAvetEtAbY8LaarqSXJH2p3vwHiuX1i3xs=,iv:eWm84HSCoGPo7DNgUOEEVrJyGyvH7MUfeQRTU0RHSgI=,tag:JESGLRIYsxjATYqRP5ppvQ==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNlRWQ2pLaXBNZEVaY0M3\neHpJNytJUldselBIM29XSnFCczZoSkwyZjBzCmdGdVJjRHJUa3Zoc1NmbUZLbEtF\ncWlOdDNMRmRkQWkxYnI4Z0xRNmIvcEkKLS0tIElrdWpsRUcxQzd4NHYrMktUNjJO\nUVhVZGNxNVRYQ3I1ZDNhdkNMTkFidlEKivM/9R805DD2tUO8wq50kYInmjMHgh0r\nRsPIFj6l0G8gE4lWQ6OZIz5GL5JmlRN+3xC2snQZIGEz05XNiS0oHQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:40Z",
		"mac": "ENC[AES256_GCM,data:WzMc4hjVV8y4Z4Fz6Kd4u9gfBVUyRulzBOtNXsDGmue7gVjP5lqcaoB50kwzs6a4LkOlYFw1EbvamBkcd6fVnm7SoYxGrM0vH2WbwUUyo+O9FdsoLArYHaLwLocSlrm+Im+5h7+kmF3tY2fO2WU/YPRuuRxk+OBny4H/DlwDf7U=,iv:42VvRAEx0god2Ap507oYWYBS96CYHBdtJ1bFk+jfsoY=,tag:bNMOuY/gRozT5+m09ESIVg==,type:str]",
		"version": "3.13.1"
	}
}
