{
	"data": "ENC[AES256_GCM,data:7H+vzM22GNpaohod0C7SfcrxPak3S0c=,iv:yFioLDgHxmOkWh47TR67ccED19ruadzvxd8VdGHrNpQ=,tag:ICqBHEe2luR/arpL9s/XBA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTFhiN0gydUFaNjRQSFRa\nYWw3RkFPdGhMem5Xdi9GQXFpOHJDVEhrdVdBClFyeU5YTmZHS25ERW5ZaitkY1ZD\nSjl3M09STHRIL2dVS0ZXQy9QZkQ4RUEKLS0tIHRYLzNQWVA2QkJGT1dxNCs1UDFa\ndlhzV1F2ZGlVbnBxL0RQdDMrQm41QUEK1Uil890ovjM69g5Yyd/vZcGg369Gu4s9\ntsnEh+cd2qaKthRNpD8ARMetRvRgaoXZzUNwBRoTBJL0LTDSqbq5DQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPb2JvV09ZVnpFOXppZTU2\nSEs3dlhVUnR0eDJ1VVAwVVVFTzFQb0gwYkJFCk5OcEpudGJlT3dmZVNsY00xN1pr\nU3ZIU2lhdjBFSkE1a2dVYjFKdHpLV3cKLS0tIG9FNU1Xem9yYnpPSmRqc2UxbjFY\nVHIxNXQybjFTSnh3UHVzS1owSVY4ZFEKnRftSZkwqzk7FNptwLEXy7I9rEdm7Nfd\nxCJ0NLVytpb4ypNFfp/nVlAJMpl9YCPaCox8/owQN4TxzrN2/v4ahw==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age163ce5qyznc8vsfq9ppkk5jwtuj66yasxup3hge2t625y4xmw5ffqcmczdx"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG9BUEY2ZyBBcGZKczhn\nZWFjT2Q4K1UxWExUOFZZZ0hTN3l6dkJuR0FXeWhpMkx6TzdHUQpjTWFoOTY0b0tL\nUGRxQVRQbUdCQjZ0eWdzNTlLNHBHWUJiRVp3ZEVBNkJVCi0tLSBUZDhBaVA2cUVa\ncGVVV0NyU2Z3KzdRMitwOHBZVnJUTk5YcmlQc1liVWVVCoOZGKgpa4xxIsNbB/1B\no2/U3LsCo0dojZYl4KDl2ESh78yzWk9a5IcOnQ6FrGqE6WuSTnzPYwaQ3z3xilRo\nGnk=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qtrfqkheehc6dlyux9stwq67dq3kcledlwzzrckx0wk639mh0wqh54auh7v"
			},
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDRmdXAvZyBBM09MREd1\nZlUwSmR0N1h5RFpGdG9pZGdvcldOakdPNHdueDIxT0xIdUl3cApna1Bsdm9GTXZU\naE1lNk9Ja1dnUlNyYTJrYmMzeDJmUW1Lb0luRDNhUWtJCi0tLSBYU3NpZ0g4ZWtQ\nZnh3b2JQcmNyVmhBUEYxV0VBaXVZdW9UeWN3KzVHRmM0Cp31fDsOZWge0vDnYW0/\nlK7zILS/fzWykbUsMAladIzsrhqZF28gyK3sliY7lhDRYIk9+fsJyuf2a6tx0Gwx\nnow=\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1yubikey1qvh5yeguawe89kr9muzn6xvfwjkcja7rf0j6afxgyula6p9vql4kkjh52h2"
			}
		],
		"lastmodified": "2026-07-25T22:31:29Z",
		"mac": "ENC[AES256_GCM,data:dCnyLgODhqLMtZpyvQrCBmpvr2FBDXlL+b8MDFL5wU5NroG3V/vcwoH0irpBwfOtPKc4K2ikgrQhyO/ERxmbmtMnUwTQqZJfqGqjxVKynPWqlJ8XwdH2ufvYgNQjbUr0vs27ijcNXzW+GXZs8YhgrzEPuXynVoSaNgWLLAMEPg8=,iv:KWJyWSSw1VrgPu784hkmoI4KUBVEEMIQqsb0LT5z0WU=,tag:pEX+a/7Ne4zJhjtHsoJW/Q==,type:str]",
		"version": "3.13.1"
	}
}
