{
	"data": "ENC[AES256_GCM,data:mZvuWf9qzm39VgA=,iv:4bShJF6QsKrMLUBik+vExJjnCexUopN7pi6kKJCuGZ0=,tag:VAJe3oOKz5rZ5AMwXKR+iA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdXZjcnBmTDJLM25oMkZW\nb1VueC9BS3g0RzM5SGVTWDIyUlpzZEVGdlhzCldpdWFIZW5SMDM5VmlVcTNiNERJ\nQlZ0aEJPQWgxa081YndmcXRxZkhJWFUKLS0tIEJkVi93dndjUUFXbVhRb0hlbHhR\nL0tLZUQ2SjFZOS9HNC9iak1DNXpValUKmPGU8FSitks3yszytsgEAWewjdXESJS0\n30ymLV+KcmeaN1qIsTeUIINmUBJ/tbqc4s3tNPuqdzed1ZgiibtGXQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1p98yp8w64rdugp03332gxnz5q2vcnucn69cs5qm6s2l2u7epqfcqmu2pqe"
			}
		],
		"lastmodified": "2026-06-09T11:59:41Z",
		"mac": "ENC[AES256_GCM,data:hmkSSVnVyBDosIaO/wIrS6Uc+AYC7/Ma273Dx3EdUWmif/pFGS6sxsd0m9KkQW1oxbUNQDDMtnCDKSSq8sHMLDokl13KjTyaU4SY+UnzIposkkODbeOpn/lmIr0AUdJSmExHRoKotjL5pJHi9C4QECKVAb8EQADC9qZ/N2/8M7g=,iv:TZ2oXmHhsSJext5FHYjnrypVqLOCoEQ1J1RHPRi6soQ=,tag:q/fXc+DiFN9oY6WJLmvHxA==,type:str]",
		"version": "3.13.1"
	}
}
